### ISSUE TITLE
Article 'Apply Entity Framework Core migrations in .NET Aspire' misses step

### ISSUE THREAD

**Issue by bertgroenveld** [dotnet/docs-aspire#1012]
### Describe the issue or suggestion

[Apply Entity Framework Core migrations in .NET Aspire](https://learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations#create-the-migration-service) misses one step. Program.cs of the MigrationService should add these lines:
`builder.AddServiceDefaults();

builder.Services.AddOpenTelemetry()
    .WithTracing(tracing => tracing.AddSource(Worker.ActivitySourceName));

builder.AddSqlServerDbContext<TicketContext>("sqldata");`

---
[Associated WorkItem - 263589](https://dev.azure.com/msft-skilling/Content/_workitems/edit/263589)

**Comment by CamSoper** [comment]
As it so happens, I'm working on this doc now! Thanks for the report, @bertgroenveld!
