### ISSUE TITLE
Walkthroughs/tutorials on using AZD to deploy an Aspire application via CI/CD in both GitHub Actions and Azure Pipelines

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#104]
We need two tutorials written:

- [x] One from the perspective of someone using AzDO (so Azure Repos + Azure Pipelines). #386
- [x] Another using GitHub and GitHub Actions to deploy an Aspire application to Azure via AZD. #228

**Comment by IEvangelist** [comment]
Closed by:

- #228
- #386
