### ISSUE TITLE
This documentation does not work

### ISSUE THREAD

**Issue by hjrb** [dotnet/docs-aspire#1041]
1.) extension method AddAzureKeyVaultSecrets does not exists after one adds Aspire.Azure.Security.KeyVault to the consuming project
2.) If you use .AddConnectionString it is MANDATORY to add this to the appsettings.json of the Aspire AppHost
  "ConnectionStrings": {
      "planit3kv": "4711"
   },
It is unclear and confusing why this is a connection. Azure Key vault and secrets are distinct from databases
3.) It is not clear if   calling AddAzureKeyVault(PlanIt3Global.AspireKeyVaultResourceName) in the Aspire AppHost will cause a key vault to be deployed (that would be what I expect) and why I would need to fiddle around with vault Uri at all

My expectation is:

1. Calling AddAzureKeyVault will trigger the creation of a Azure Key vault resource and access to it will be granted automatically
2. There should be an API where I can add a secret similar to e.g. adding an parameter (AddParameter). The secret should be taken from the configuration so I can safely persist the secret in secrets.json
3. The example documentation should actually be written free of prior knowledge. Please describe everything that happens instead of just a couple of aspects.

---
[Associated WorkItem - 261688](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261688)

**Comment by IEvangelist** [comment]
Hi @hjrb - thank you for taking the time to post this issue. Let me see if I can be of some assistance.

> 1.) extension method AddAzureKeyVaultSecrets does not exists after one adds Aspire.Azure.Security.KeyVault to the consuming project

Do you have a `using Microsoft.Extensions.Hosting;` statement at the top of the file? This does exist as an API, and the [source code](https://github.com/dotnet/aspire/blob/d215c528c07c7919c3ac30b35d92f4e51a60523b/src/Components/Aspire.Azure.Security.KeyVault/AspireKeyVaultExtensions.cs#L76) and [API references are listed as well](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.aspirekeyvaultextensions.addazurekeyvaultsecrets?view=dotnet-aspire-8.0#microsoft-extensions-hosting-aspirekeyvaultextensions-addazurekeyvaultsecrets(microsoft-extensions-configuration-iconfigurationmanager-system-string-system-action((aspire-azure-security-keyvault-azuresecuritykeyvaultsettings))-system-action((azure-security-keyvault-secrets-secretclientoptions))-azure-extensions-aspnetcore-configuration-secrets-azurekeyvaultconfigurationoptions)).

> If you use `.AddConnectionString` it is MANDATORY to add this to the _appsettings.json_ of the Aspire AppHost:
>
> ```json
> "ConnectionStrings": {
>   "planit3kv": "4711"
> },
> ```

It's not required for it be in the _appsettings.json_, it could be a user secret, or an environment variable. Either of those configuration sources would be preferred over sitting in the JSON file.

> It is unclear and confusing why this is a connection. Azure Key vault and secrets are distinct from databases.

This is the way the Azure Key Vault has always worked. You need a connection string to communicate with it, once you have that it acts as a configuration source, flowing secrets and other configuration through to your app as needed.

> It is not clear if calling `AddAzureKeyVault(string name)` in the Aspire AppHost will cause a key vault to be deployed (that would be what I expect) and why I would need to fiddle around with vault Uri at all

This is good feedback. Anything you do with the app host needs to be explicit. Did you read through the [App Host docs](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?tabs=docker)? They explain how all of this comes together... What could we do to make it more clear?

**Comment by hjrb** [comment]
Hi, I got this link with and alternative documentation https://github.com/dotnet/aspire/blob/main/src/Components/Aspire.Azure.Security.KeyVault/README.md
This is also wrong

This works: 

In the Aspire host do:
// we only need the key value only when publishing, local development use secrets instead as we can not create a local key vault instance
if (builder.ExecutionContext.IsPublishMode) { 
       // it is a resource. name it accordingly
       // for better understanding: this will CREATE a key vault instance in Azure when deploying. For local use we can use secrets
	var keyVaultResource = builder.AddAzureKeyVault(<keyvalutName>);
	server.WithReference(keyVaultResource);
}
// no need to add anything to the appsettings.json for the host

In the consuming application add
if (builder.Environment.IsProduction()) {
	// use key vault for secrets - this is an extension method for the Configuration - not for the builder
	builder.**Configuration**.AddAzureKeyVaultSecrets(<keyvalutName>);
        // or use
	//builder.AddAzureKeyVaultClient(<keyvalutName>);
}

The "ConnectionString" wording is for me very confusing. in the old days a connection string was for a DB connection - not for a Uri pointing to a key vault. But maybe that is the new way to talk.
I would completely remove the connection string. Not required. You would not know what to put into the ConnectionString.

Aspire will create the Key Vault resource on deployment. Its name is random. You can not know the name before it has been deployed. The idea of Aspire is that you do not need to take of these magic connection strings at all.

IMHO adding LOTS of comments with intention to documetation is a good practice

**Comment by hjrb** [comment]
Hi, I got this link with and update documentation https://github.com/dotnet/aspire/blob/main/src/Components/Aspire.Azure.Security.KeyVault/README.md
This is also wrong
This works: 
In the Aspire host do:
// we only need the key value only when publishing, local development use secrets instead as we can not create a local key vault instance
if (builder.ExecutionContext.IsPublishMode) { 
       // it is a resource. name it accordingly
       // for better understanding: this will CREATE a key vault instance in Azure when deploying. For local use we can use secrets
	var keyVaultResource = builder.AddAzureKeyVault(<keyvalutName>);
	server.WithReference(keyVaultResource);
}
// no need to add anything to the appsettings.json for the host

In the consuming application add
if (builder.Environment.IsProduction()) {
	// use key vault for secrets - this is an extension method for the Configuration - not for the builder
	builder.**Configuration**.AddAzureKeyVaultSecrets(<keyvalutName>);
        // or use
	//builder.AddAzureKeyVaultClient(<keyvalutName>);
}

The "ConnectionString" wording is for me very confusing. in the old days a connection string was for a DB connection - not for a Uri pointing to a key vault. But maybe that is the new way to talk.

**Comment by IEvangelist** [comment]
Closed by #1042 and https://github.com/dotnet/docs-aspire/issues/1041#issuecomment-2150040749. As for the other parts of this, they're really product concerns, such as the confusion around overloading the term connection string.
