### ISSUE TITLE
[New article]: Redis-like article but for Valkey + Aspire.StackExchange.Redis

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#1049]
### Proposed topic or title

Using Valkey with .NET Aspire

### Location in table of contents.

Next to the Redis articles

### Reason for the article

We are introducing support for Valkey in this PR:

https://github.com/dotnet/aspire/pull/4324

It is presently a drop in alternative for Redis. We probably need an article that sites right alongside the Redis articles so that folks who might be looking for Redis content to understand how Valkey works can find it.

### Article abstract

The article should cover:

1. AddValkey
2. WithDataVolume/WithBindMount
3. WithPersistence

It can probably cover off the client side pieces by just referring back to the Redis article although the Redis article might need to more clearly call out which is service code and which is app host code.

Configuring Valkey using AddValkey and using the data volume and persistence extension methods.

### Relevant searches

valkey, redis

---
[Associated WorkItem - 288126](https://dev.azure.com/msft-skilling/Content/_workitems/edit/288126)

**Comment by eerhardt** [comment]
Can we use this issue for Garnet as well? It falls into the exact same category as above. They are basically duplicates of each other, except one is for Garnet and one is for Valkey, but all the API and content is basically the same.

https://github.com/dotnet/aspire/pull/3839 added Garnet support.
