### ISSUE TITLE
[Components] New Azure WebPubSub component article 

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs-aspire#1058]
### Describe the issue or suggestion

**Help us make content visible**

**Describe the new article**

We added a new `Aspire.Azure.Messaging.WebPubSub` component and `Aspire.Hosting.Azure.WebPubSub` hosting library in `main`. See:

* https://github.com/dotnet/aspire/issues/1063
* https://github.com/dotnet/aspire/pull/2495
* https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Azure.Messaging.WebPubSub

cc @IEvangelist @vicancy

**Comment by IEvangelist** [comment]
Closed by #1484
