### ISSUE TITLE
Following Quickstart leads to unclear error 

### ISSUE THREAD

**Issue by sanelson832** [dotnet/docs-aspire#1068]
On Mac Following the quickstart guide (using Visual Studio Code) will lead to an error involving an unsecure certificate, which is not mentioned anywhere on the quickstart page (https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?pivots=vscode) 

And once I found the page that I think is supposed to have a resolution (hidden under the troubleshooting submenu on the side), following those steps did not resolve the issue https://learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/untrusted-localhost-certificate

At the very least there should be a warning on the quickstart page since this ticket (https://github.com/dotnet/aspire/issues/2914) seems to suggest that it will happen on any linux/mac environment

**Comment by IEvangelist** [comment]
Thank you for posting this issue @sanelson832, I have a PR #1087 in place that help address this concern.
