### ISSUE TITLE
Include note that project reference names must be lowercase

### ISSUE THREAD

**Issue by jongalloway** [dotnet/docs-aspire#1094]
### Describe the issue or suggestion

Related to https://github.com/dotnet/aspire/issues/4505

Apparently the container app names are generated based on the `name` property in the *AppHost* project reference. Uppercase characters cause deployment failures with the following message:

```text
6/13/2024 2:20:49 PM: Info   (x) Failed: Deploying service WebFrontEnd
6/13/2024 2:20:49 PM: Error failed deploying service 'WebFrontEnd': updating container app service: applying manifest: PUT https://management.azure.com/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/rg-aspire-deployment-repro/providers/Microsoft.App/containerApps/WebFrontEnd
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: ContainerAppInvalidName
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ContainerAppInvalidName",
    "message": "Invalid ContainerApp name 'WebFrontEnd'. A name must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character and cannot have '--'. The length must not be more than 32 characters."
  }
}
--------------------------------------------------------------------------------
```

We should include notes on this in both the [deployment](https://learn.microsoft.com/dotnet/aspire/deployment/azure/aca-deployment-visual-studio) and [AppHost](https://learn.microsoft.com/dotnet/aspire/fundamentals/app-host-overview) docs.

---
[Associated WorkItem - 264635](https://dev.azure.com/msft-skilling/Content/_workitems/edit/264635)

**Comment by jamesmontemagno** [comment]
I think the other thing is the length as well.. @csharpfritz  mentioned that one of his names was too long and it got chopped off and then was no longer valid.
