### ISSUE TITLE
Common FAQ: Adding projects from other solutions

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/docs-aspire#1097]
### Describe the issue or suggestion

Do we have guidance or an answer for this? I do seem to get it a lot and having it in the FAQ or in orchestration guide may be nice to have.

---
[Associated WorkItem - 297231](https://dev.azure.com/msft-skilling/Content/_workitems/edit/297231)

**Comment by IEvangelist** [comment]
What's the specific question here, is it, "how do you add projects to other solutions"? Are you asking about the templates?

**Comment by jamesmontemagno** [comment]
I often get a question...

I have multiple solutions (backend solution and a frontend solution) or in different repos. How would I add on of the projects from another solution or repo into my app host to have it startup too.

Answers... I assume you can just reference the project location? I told folks add a submodule...

**Comment by jamesmontemagno** [comment]
For sure! Even if it is like hey... create a new solution with all of your projects and leverage project filters or something... idk
