### ISSUE TITLE
Rename "Build .NET Aspire apps with Node.js"

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/docs-aspire#1098]
### Describe the issue or suggestion

https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs

In this doc I think there are 2 things that could be improved:

1. There is no such thing as a .NET Aspire app... 
2. It makes it sound like you are using JS to build a .NET Aspire project

I think really this should go under orchestration and just be a document:

"Integrate Node.js and npm apps" or "Use Node.js and npm apps"

Thoughts?

**Comment by IEvangelist** [comment]
Was this fixed by one of your PRs?

**Comment by IEvangelist** [comment]
Closed by #1100

**Comment by jamesmontemagno** [comment]
It was ;) you caught me :)
