### ISSUE TITLE
Explain how to use aspire when deploying to a location that does not have built in tooling

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs-aspire#1116]
There are LOTS of questions around how to deploy and run aspire outside of azure or outside of a Kubernetes based environment. Today aspire relies on deployment tools to extract the manifest from the apphost and translate it to some set of assets that can be applied to the deployment environment.

https://github.com/dotnet/aspire/discussions/1439#discussioncomment-8267781

In absence of this, we have no tooling story for users deploying to custom environments in the box. They can either build custom tooling or deploy like they were doing before.

This might be FAQ content.

---
[Associated WorkItem - 297230](https://dev.azure.com/msft-skilling/Content/_workitems/edit/297230)

**Comment by IEvangelist** [comment]
We do already have content on the manifest, that explains how tool builders might use it. And we do have various degrees of deployment content with the currently supported tooling. If this was a FAQ, I'd likely just link to those bits as we don't really have anything else to say about this yet, right?
