### ISSUE TITLE
.NET 8 Aspire GitHub Actions to just deploy to existing Azure resources. Do not provision

### ISSUE THREAD

**Issue by vishipayyallore** [dotnet/docs-aspire#1117]
### Describe the issue or suggestion

Team,
I was trying the .NET 8 Aspire GitHub actions. It was working when we have single job. I wanted to split into three jobs, that is when it started failing.

Error Message:
```
Run azd deploy --environment dev --no-prompt
Analyzing Aspire Application (this might take a moment...)

Deploying services (azd deploy)

Deploying service apiservice
Deploying service apiservice (Logging in to registry)
Deploying service apiservice (Pushing container image)
Deploying service apiservice (Updating container app)
  (x) Failed: Deploying service apiservice

ERROR: failed deploying service 'apiservice': failed executing template file: template: containerApp.tmpl.yaml:2:[1](https://github.com/ViswanathaSwamy-PK-TechSkillz-Academy/simple-dotnet-aspire/actions/runs/9551637934/job/26326472684#step:9:1)7: executing "containerApp.tmpl.yaml" at <.Env.AZURE_LOCATION>: map has no entry for key "AZURE_LOCATION"
```

GitHub URL: https://github.com/ViswanathaSwamy-PK-TechSkillz-Academy/simple-dotnet-aspire

![image](https://github.com/dotnet/docs-aspire/assets/8255269/44d91a81-5add-40ce-b301-4d216c1b369f)

![image](https://github.com/dotnet/docs-aspire/assets/8255269/3b41f836-b29f-48e7-9c4b-ecb6d0050138)

---
[Associated WorkItem - 280346](https://dev.azure.com/msft-skilling/Content/_workitems/edit/280346)

**Comment by davidfowl** [comment]
cc @vhvb1989

**Comment by vishipayyallore** [comment]
@vhvb1989 CC: @davidfowl 
Victor,
Thank you so much. Your updated code works. One small change I made was added --no-prompt. Many thanks.

```
      - name: Refresh azd env (pulls latest infrastructure provision)
        run: azd env refresh --no-prompt
        env:
          AZURE_LOCATION: ${{ env.AZURE_LOCATION }}

```

![image](https://github.com/dotnet/docs-aspire/assets/8255269/aab1273e-238c-457c-a3f3-fe1af5762964)

**Comment by vhvb1989** [comment]
@vishipayyallore Yeah, since the provision and deploy operations are happening in separated stages, the azd env refresh is required there to make the connection. :)

**Comment by vishipayyallore** [comment]
> @vishipayyallore Yeah, since the provision and deploy operations are happening in separated stages, the azd env refresh is required there to make the connection. :)

Really appreciate your help Sir @vhvb1989 .

**Comment by davidfowl** [comment]
@vhvb1989 Do we need to update docs?
