### ISSUE TITLE
Endpoint looks iffy

### ISSUE THREAD

**Issue by 9Rune5** [dotnet/docs-aspire#112]
### Type of issue

Missing information

### Description

> The "dashboard" endpoint, resolved via http://_dashboard.basket is _dashboard.10.2.3.4:9999.

Isn't the "dashboard" endpoint simply `10.2.3.4:9999`?

If my guess is wrong, then I am obviously missing something fundamental. In that case I would be ever so grateful if the article was a bit clearer on what is going on. (what happens behind the scenes and what is observed where)

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/service-discovery/overview

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/service-discovery/overview.md

### Document Version Independent Id

c250cb89-e0b4-c037-e4e0-edcec7c84eb8

### Article author

@IEvangelist

**Comment by IEvangelist** [comment]
Let's ask @ReubenBond about this one, I know it's accurate - but we should probably explain in better here in docs.

**Comment by ReubenBond** [comment]
I opened https://github.com/dotnet/docs-aspire/pull/135 to fix, thanks for reporting @9Rune5
