### ISSUE TITLE
Expand testing docs

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/docs-aspire#1151]
### Describe the issue or suggestion

As we add a new `GetEnvironmentVariableValuesAsync` method in https://github.com/dotnet/aspire/pull/4530,

the [testing section](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/testing) could be expanded.

I'm not sure it is the only thing we should capture.

**Comment by IEvangelist** [comment]
Closing as a duplicate of #1114
