### ISSUE TITLE
[Aspire] Names vary across layers

### ISSUE THREAD

**Issue by amcasey** [dotnet/docs-aspire#12]
What we doc as the orchestrator is called the "AppHost" in the project name and the "AspireHost" in msbuild.
What we doc as configuration (I think) is called "ServiceDefaults" in the project name and "AspireSharedProject" in msbuild.

**Comment by IEvangelist** [comment]
I don't think we call out anything specific to MSBuild in the docs, could you please find a link to where we're doing that?

**Comment by amcasey** [comment]
We show project file segments with property names `IsAspireHost` and `IsAspireSharedProject`.

**Comment by IEvangelist** [comment]
Right, ok. I think those are fine - it's only in two places and it's explaining the XML. Outside that, we are consistent. Changing those properties would be a product concern, not docs. I'll close this.
