### ISSUE TITLE
[Aspire] I can't figure out what Configuration is

### ISSUE THREAD

**Issue by amcasey** [dotnet/docs-aspire#13]
The Overview docs mention configuration without really explaining what that is.  Is it related to `IConfiguration`?  Is it declarative yaml/json/xml files (I don't think so)?  Is it component-specific?

A couple particularly confusing bits:

> Applies ServiceBusClient configurations either inline through code or through configuration

> capable of flowing their configurations through dependencies

**Comment by IEvangelist** [comment]
I think this has been fixed, as I cannot find this content.
