### ISSUE TITLE
For Aspire preview.2, some more updates are needed to the setup instructions using VS / CLI with aspire

### ISSUE THREAD

**Issue by balachir** [dotnet/docs-aspire#130]
**Issue description**
In the .NET Aspire setup and tooling doc, we need to make some more updates to the instructions for Preview 2.

[Setup using CLI](https://learn.microsoft.com/en-us/dotnet/aspire/setup-tooling?tabs=dotnet-cli)

- [x] During validation, we have been doing `dotnet workload update` first and then run `dotnet workload install aspire`. But the documentation asks users to run `dotnet workload install aspire` first and then run `dotnet workload update`. 

[Setup using VS](https://learn.microsoft.com/en-us/dotnet/aspire/setup-tooling?tabs=visual-studio)

- [x] In the VS installer steps, after the step `Modify to install the .NET Aspire component`, we should additionally ask the user to run `dotnet workload update` and `dotnet workload install aspire` from a Command prompt. With VS 17.9 Preview 2, the installer will continue to include only the preview.1 version of aspire. So, users need to use the CLI to get the latest preview.2 version of aspire.

- [x] In the [Add orchestration projects](https://learn.microsoft.com/en-us/dotnet/aspire/setup-tooling?tabs=visual-studio#add-orchestration-projects) section, the screenshot of the `Add .NET Aspire Orchestrator Support` dialog needs to be updated. The `Framework` dropdown in this dialog has been removed in preview.2.

- Couple of screenshots need to be updated
    - [x] Aspire Sample Dashboard screenshot should be updated. With preview.2, the Projects, Containers and Executables tabs are combined into one section.
    - [ ] [Minor nit] In NuGet Package manager for Add Aspire Component, the packages show preview.1 instead of preview.2. I'm not sure if we plan to keep updating this screenshot for each preview.

**Comment by balachir** [comment]
@joperezr for my comment above for the 'Setup using CLI' part, is there a particular order that you recommend for those commands?

**Comment by joperezr** [comment]
Theoretically the right order is `dotnet workload update` and then `dotnet workload install aspire`. Reason is that `dotnet workload update` will go and update all of the baseline workload manifests you have inside the SDK (a workload manifest is not the workload itself, but simply a "reference" to it which describes which things compose it and what needs to be downloaded if the workload is to be installed), and once those manifests are on their latest version, then you can run `dotnet workload install aspire` which will then go and download the packs and install them.

That said, I believe in most cases when running `dotnet workload  install aspire` that would also go and internally call `update` if needed, so it is possible that install alone would be sufficient. That said, this depends on when was the last time that the SDK in the background did a advertising manifest update, so the safest thing is to run update first and then install.

**Comment by joperezr** [comment]
Preview 2 packages will show in nuget.org after we ship it. To see them in the package manager _before_ we release, you just need to add the package source: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

**Comment by alistairmatthews** [comment]
> Preview 2 packages will show in nuget.org after we ship it. To see them in the package manager _before_ we release, you just need to add the package source: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

Thanks @joperezr. I think we'll put up with the old version numbers.

To resolve some conflicts I've closed the original PR and created this new one: #208 

Should be ready to merge.
