### ISSUE TITLE
New Elasticsearch article

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs-aspire#1379]
We added 2 new libraries to Aspire:

* Aspire.Hosting.Elasticsearch
* Aspire.Elastic.Clients.Elasticsearch

See https://github.com/dotnet/aspire/pull/4430 for more details.

We should add an article on Elasticsearch and how to use it in .NET Aspire.

**Comment by IEvangelist** [comment]
Duplicate of #1059
