### ISSUE TITLE
How to write custom exception in dot net aspire

### ISSUE THREAD

**Issue by AjayShaktawat** [dotnet/docs-aspire#1383]
try
{
    var dd = 1;
    var ff = 0;
    var temp = dd / ff;
}
catch(Exception ex)
{
    Console.Write(ex.Message);
}

in above code I want to write catch block exception in dot net aspire

**Comment by IEvangelist** [comment]
Hi @AjayShaktawat - I'm not sure I follow your ask. Why are you trying to write a custom exception? It's easy to do, and it's not something that is specific to .NET Aspire.

```cs
using System;

try
{
    throw new MyCustomException("Custom error");
}
catch (MyCustomException ex)
{
    Console.Write(ex.Message);
}

public class MyCustomException(string message) : Exception(message)
{
}
```

[Here's a link to the Sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWAChiFkBPYgb2IAJ7aEALZAewHdaYBTTgWXIBhVAGcErMAFEAHgGNuABwRRWMABQAiYWIm1uyNsg0BKANzEAvsVkQEsprTUDt4qXMXLVe6cep0GgqoirAA23AB0AOrIUAjcatzS4XzcIiIQAObcZpbExFgAzLS4tM6irjLySirqWHgADLRgqelZxrQgtJUeNWrNaZnZfkQWQA).
