### ISSUE TITLE
[Aspire] Dashboard section introduces new terminology without definition

### ISSUE THREAD

**Issue by amcasey** [dotnet/docs-aspire#14]
The Dashboard section seems to take for granted that the preceding text will have explained what Containers and Executables are, but I don't think we actually mention containerization anywhere.  At first, I thought each project was a container, but the example clarifies that projects are Projects and components like Redis get Containers.  I don't know what an Executable is - all the doc says is that the sample app doesn't have any.

**Comment by IEvangelist** [comment]
Closing this one, as we're starting fresh... and the terms are defined inline for each section.
