### ISSUE TITLE
Add metrics exemplars to explore metrics page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs-aspire#1407]
### Describe the issue or suggestion

There are docs that explore the metrics page. A new feature in 8.1 is metrics exemplars: https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/explore#metrics-page

---
[Associated WorkItem - 292422](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292422)

**Comment by IEvangelist** [comment]
Yes, OTEL - exemplars: https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exemplars
