### ISSUE TITLE
Add clarity in the documentation

### ISSUE THREAD

**Issue by pjbhakta-outlook** [dotnet/docs-aspire#147]
### Type of issue

Missing information

### Description

It would be nice to clarify which project should we include provided code in - i.e. apphost project or your project or extension project. Reading the code, it's not clear where should we add package refereances, where we should add code snipets etc.
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-entity-framework-component?tabs=dotnet-cli

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/database/azure-cosmos-db-entity-framework-component.md

### Document Version Independent Id

8b585800-8c7b-df72-3125-2776e1b1375e

### Article author

@IEvangelist

---
[Associated WorkItem - 214421](https://dev.azure.com/msft-skilling/Content/_workitems/edit/214421)

**Comment by IEvangelist** [comment]
This issue was addressed as part of #314. During the restructuring of these articles, we help to disambiguate projects, such as the component consuming projects and app host projects.
