### ISSUE TITLE
Mention `WithPgWeb` in Postgresql docs

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/docs-aspire#1472]
We Add the `WithPgWeb` public API in https://github.com/dotnet/aspire/pull/5098.

This API Adds `pgweb` container to the app host.

we should mention this API and how to use it in posgresql docs

---
[Associated WorkItem - 300675](https://dev.azure.com/msft-skilling/Content/_workitems/edit/300675)

**Comment by IEvangelist** [comment]
@Alirexaa - Is this related to release 8.2?

**Comment by Alirexaa** [comment]
> @Alirexaa - Is this related to release 8.2?

The related PR has not merged yet but yes.

**Comment by Alirexaa** [comment]
@IEvangelist, The related PR has been merged. This will be part of the next release.
