### ISSUE TITLE
Mention `WithRedisInsight` in Redis docs

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/docs-aspire#1474]
We Add the `WithRedisInsight` public API in https://github.com/dotnet/aspire/pull/5227.

This API Adds `RedisInsight` container to the app host.

we should mention this API and how to use it in Redis docs

**Comment by IEvangelist** [comment]
@Alirexaa - Is this related to release 8.2?

**Comment by Alirexaa** [comment]
> @Alirexaa - Is this related to release 8.2?

The related PR has not merged yet but yes.

**Comment by Alirexaa** [comment]
@IEvangelist, The related PR has been merged and will be part of release 9.
