### ISSUE TITLE
Update Milvus Aspire docs to reflect auth config and minimum versions support

### ISSUE THREAD

**Issue by timheuer** [dotnet/docs-aspire#1475]
### Describe the issue or suggestion

See [dotnet/aspire#4966](https://github.com/dotnet/aspire/issues/4966) for details. Milvus enabled authentication configuration similar to other Aspire resources. The docs at https://github.com/dotnet/docs-aspire/blob/main/docs/database/milvus-component.md would need to be updated to reflect the configuration requirement and password usage.

---
[Associated WorkItem - 300674](https://dev.azure.com/msft-skilling/Content/_workitems/edit/300674)

**Comment by IEvangelist** [comment]
@timheuer is this a release 8.2 request, or just general?

**Comment by timheuer** [comment]
This would be for the next release
