### ISSUE TITLE
[New article]: Conceptual docs for new eventing API

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#1478]
### Proposed topic or title

.NET Aspire eventing and orchestration

### Location in table of contents.

Fundamentals

### Reason for the article

In https://github.com/dotnet/aspire/issues/5234 (issue) and https://github.com/dotnet/aspire/pull/5223 (PR) we are introducing a new API that allows developers to subscribe to lifecycle events. The idea is that we have an extensible local eventing mechanism to support orchestration. We might use it to trigger an action once a database container is online so we can initialize the database.

### Article abstract

The article will need to introduce IDistributedApplicationEventing and how to publish and subscribe to events. It should show how to subscribe to events globally, and how to subscribe to resource-specific events (which can also be subscribed globally).

---
[Associated WorkItem - 308090](https://dev.azure.com/msft-skilling/Content/_workitems/edit/308090)

**Comment by IEvangelist** [comment]
@mitchdenny is this a release 8.2 request?

**Comment by mitchdenny** [comment]
No. This work is building up for 9.0

**Comment by mitchdenny** [comment]
This API will ship in 8.2, but we don't need to go out of our way to document it until 9.0 because its experimental.

**Comment by davidfowl** [comment]
I think this should be under AppHost not Fundamentals
