### ISSUE TITLE
Remove note on 9.0 SDK limitations for 9.0 prerelease

### ISSUE THREAD

**Issue by joperezr** [dotnet/docs-aspire#1573]
For our next 9.0 prerelease, we plan on fixing the issue with project templates as well as project targeting that we previously had, so this section should be modified/fixed by then:

https://github.com/dotnet/docs-aspire/blob/44a95e62c90392ed9cfce321047fb167c9fc109d/docs/fundamentals/setup-tooling.md?plain=1#L154-L155

**Comment by IEvangelist** [comment]
Ok, when is the next 9.0 prerelease happening? Is that part of the 8.2 rollout? /cc @joperezr

**Comment by joperezr** [comment]
Snap is scheduled tomorrow: 8/30
Build should be done by: 9/5
Release is scheduled for: 9/10

**Comment by sunnynagavo** [comment]
https://github.com/dotnet/docs-aspire/pull/1580 

merge it only after Pre-release.
