### ISSUE TITLE
SFI-related efforts

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs-aspire#1594]
### Describe the issue or suggestion

Issue for tracking any and all SFI-related efforts for this sprint.

- [x] Address **Security: Code scanning alerts**
- [x] Fill internal tool survey:
  - [x]  .NET Version sweeper
  - [x] Status Checker
- [x] Work on triage with @gewarren
- [x] https://github.com/dotnet/docs/pull/42559
- [x] #1695

---
[Associated WorkItem - 308082](https://dev.azure.com/msft-skilling/Content/_workitems/edit/308082)

**Comment by IEvangelist** [comment]
- Participated in "Container and images security meeting"

**Comment by cmastr** [comment]
Talked to David, this is for September, so closing.
