### ISSUE TITLE
[New article]: App host configuration

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs-aspire#1602]
### Proposed topic or title

App host configuration

### Location in table of contents.

App Host

### Reason for the article

The app host can be configured by setting values in launchSettings.json, e.g. https://github.com/dotnet/aspire/blob/9a59d122949de428321599c503da59c54fb673d6/playground/BrowserTelemetry/BrowserTelemetry.AppHost/Properties/launchSettings.json#L8-L15

I don't believe this are documented anywhere. The page can follow what the [dashboard configuration](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?tabs=bash) page does.

### Article abstract

Details about the configuration values for the app host.

**Comment by IEvangelist** [comment]
We have this content for it now, perhaps we could expand this?

https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/launch-profiles

**Comment by JamesNK** [comment]
That mainly focuses on launch profiles for project resources.

There should be a doc that details the config options that can be added to the host launchSettings.json
