### ISSUE TITLE
Add IDistributedApplicationLifecycleHook docs

### ISSUE THREAD

**Issue by cecilphillip** [dotnet/docs-aspire#1613]
### Describe the issue or suggestion

There isn't currently any coverage, that I have found, around `IDistributedApplicationLifecycleHook`. Consider adding an article under the Extensibility section that discusses

* The Aspire lifecycle
* Use cases and implementation guidance on `IDistributedApplicationLifecycleHook`

---
[Associated WorkItem - 335638](https://dev.azure.com/msft-skilling/Content/_workitems/edit/335638)

**Comment by davidfowl** [comment]
We may want to prioritize the new [eventing APIs](https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?tabs=windows&pivots=vscode#eventing-model)
