### ISSUE TITLE
Add trusting ASP.NET Core localhost certificate

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/docs-aspire#1851]
When you go through this for the first time on a "clean" machine, aka new to .NET for VS Code, you run need to trust the ASP.NET Core localhost certificate before running the app. This is not explicitly stated in the VS Code version of the docs. Thankfully, the product has a popup that detects that this has not been done and asks you to accept. The screenshots for this should be added to the tutorial. 

Right after going through this step and hitting F5 however, the browser tabs launched but we got an error where it said the web page could not be loaded. We should put some screenshots on what to look for to help uses understand that there is now a cert issue like adding screenshots of the URL that shows the https crossed out with the red line. In addition, we should make it more bold and within these actual instructions themselves that users may need to close their browsers/kill the processes. I ended up on the troubleshooting docs and the instruction was hard to miss since the code to run in the terminal caught my attention right away. 

---
[Associated WorkItem - 327976](https://dev.azure.com/msft-skilling/Content/_workitems/edit/327976)

**Comment by IEvangelist** [comment]
Where would you expect this content - we do have this article, and we link to it from a few key places:

https://learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/untrusted-localhost-certificate
