### ISSUE TITLE
Document 9.0 breaking changes

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs-aspire#1868]
### Describe the issue or suggestion

Issues and PRs are tagged with breaking change. Should include details somewhere upon release.

See https://github.com/dotnet/aspire/issues?q=sort%3Aupdated-desc+label%3Abreaking-change+

cc @joperezr 

---
[Associated WorkItem - 330863](https://dev.azure.com/msft-skilling/Content/_workitems/edit/330863)

**Comment by IEvangelist** [comment]
We're writing an upgrade article, and we plan to capture all of these breaking changes in that content. We want to capture everything coming from .NET Aspire 8 and going to .NET Aspire 9, that link you provided seems to include things that were breaking changes in 8.

**Comment by JamesNK** [comment]
That list is combined for all releases. Maybe you could figure out based on milestone, but most probably won't have a milestone 🤷
