### ISSUE TITLE
[New article]: Article for incoming Meilisearch Hosting in .NET Aspire Community Toolkit

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/docs-aspire#1872]
### Proposed topic or title

Add Meilisearch in .NET aspire apps

### Location in table of contents.

Community Toolkit

### Reason for the article

In  .NET Aspire Community Toolkit we are adding support to Meilisearch hosting.

https://github.com/CommunityToolkit/Aspire/pull/66

### Article abstract

This article should explain how to use Meilisearch in aspire apps including adding Meilisearch resources to the app host and how to use the Meilisearch client in API service.

**Comment by aaronpowell** [comment]
@Alirexaa do you want to get started on this when the integration is ready and I can help you refine it?

**Comment by davidfowl** [comment]
Just an FYI, we're rewriting all of the integration docs (well @IEvangelist is), we should follow the new format. See rabbitmq for an example.

**Comment by Alirexaa** [comment]
> @Alirexaa do you want to get started on this when the integration is ready and I can help you refine it?
> 

Yes, I do.
