### ISSUE TITLE
[Community Toolkit] Deno

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/docs-aspire#1889]
### Proposed topic or title

Deno

### Location in table of contents.

integrations/community toolkit/deno

### Reason for the article

We've had a contribution for a Deno hosting integration for Community Toolkit.

### Article abstract

Overview of using Deno hosting integration.

**Comment by aaronpowell** [comment]
@brian-guerrero are you in a position to write the doc for the Deno integration, otherwise I can create the initial draft and have it up for review

**Comment by brian-guerrero** [comment]
I should be able to get a PR for this tonight in CST.

**Comment by brian-guerrero** [comment]
@aaronpowell PR is open. Looks like Deno NuGet is not published, but I linked to what it should be in documentation.

**Comment by aaronpowell** [comment]
> [@aaronpowell](https://github.com/aaronpowell) PR is open. Looks like Deno NuGet is not published, but I linked to what it should be in documentation.

Yep, I have to wait for .NET Foundation to approve the package (I've submitted the request), so it'll be there _soon_
