### ISSUE TITLE
Update Ollama for Aspre 9

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/docs-aspire#2007]
For the Aspire 9 release of the Ollama Community Toolkit integrations we have quite a large overhaul coming (see https://github.com/CommunityToolkit/Aspire/discussions/194).

The docs here need to be updated to reflect those changes.

**Comment by IEvangelist** [comment]
Would you mind deleting this issue and instead creating a breaking-change issue, [based on this template please](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)?
