### ISSUE TITLE
[WebToolsE2E][Multiple docs] The "Install .NET Aspire" section in the ".NET Aspire setup and tooling" document should be based on Aspire 9.0.0 instead of Aspire 8.

### ISSUE THREAD

**Issue by ymmendoza** [dotnet/docs-aspire#2021]
### **Describe the issue or suggestion**

Issue description
We need to update the instructions in the "[.NET Aspire tooling - .NET Aspire | Microsoft Learn](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?branch=pr-en-us-1867&tabs=windows&pivots=visual-studio#install-net-aspire)" document.

Code Resources: https://github.com/dotnet/docs-aspire/blob/70510f8794568e4a5f1e75b32752cfb50fd6afa3/docs/fundamentals/setup-tooling.md?plain=1#L29C2-L29C99

Issue1:
This version should change to 17.12 instead of 17.9
![Image](https://github.com/user-attachments/assets/25ce11ba-19a8-4a5b-9d9b-56d830897cee)

Issue 2: 
VS 17.12 includes Aspire 9.0 templates instead of .NET Aspire SDK by default
![Image](https://github.com/user-attachments/assets/e155d207-8f14-404d-b6c3-2ef459603ff5)

Issue 3:
.NET Aspire SDK does not need to be mentioned as a prerequisite because it's a NuGet package.

Issue 4: 
A note should be added before this section, such as "If you want to use Aspire 8.2.2, you can install the . NET Aspire SDK according to the steps below"
![Image](https://github.com/user-attachments/assets/b100643e-ac4c-4682-a20c-fc153e51f857)

 

---
[Associated WorkItem - 341101](https://dev.azure.com/msft-skilling/Content/_workitems/edit/341101)

**Comment by davidfowl** [comment]
Aspire 9 hasn't shipped yet see https://github.com/dotnet/docs-aspire/pull/1867

**Comment by davidfowl** [comment]
Oh was this using the draft? 

cc @IEvangelist

**Comment by balachir** [comment]
Added one additional issue to the list above regarding .NET Aspire SDK not needing to be mentioned as a prerequisite.

**Comment by IEvangelist** [comment]
This is fixed.
