### ISSUE TITLE
[Community Toolkit New article]: SQL Databases Projects

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/docs-aspire#2038]
### Proposed topic or title

SQL Databases Projects

### Reason for the article

We've had a contribution for SQL Databases Projects hosting integration for Community Toolkit.

### Article abstract

Overview of using SQL Databases Projects hosting integration.

**Comment by Alirexaa** [comment]
cc @ErikEJ @jmezach

**Comment by ErikEJ** [comment]
@jmezach Happy to create a PR for this?

**Comment by jmezach** [comment]
Sure. Is there some template I could use as a starting point?

**Comment by ErikEJ** [comment]
@jmezach Sorry, I meant; I am happy to create a PR 😄
