### ISSUE TITLE
[WebToolsE2E] .NET Aspire Support Policy page needs to be updated.

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/docs-aspire#2046]
.NET Aspire Support Policy page https://dotnet.microsoft.com/en-us/platform/support/policy/aspire needs to be updated.

![Image](https://github.com/user-attachments/assets/8ba3ae83-d1aa-4449-8f77-3021ed1af3a2)

**Comment by balachir** [comment]
@joperezr can you help re-direct this to the right person, please? Thanks!

**Comment by IEvangelist** [comment]
Attention @mairaw

**Comment by joperezr** [comment]
I'm doing this today :)

**Comment by joperezr** [comment]
https://github.com/dotnet/website/pull/7097

**Comment by v-elenafeng** [comment]
Checked this is all good now.
