### ISSUE TITLE
[Community Toolkit New article]: Python extensions

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/docs-aspire#2091]
### Proposed topic or title

Python Extensions

### Reason for the article

New package in the community toolkit that provides extensions on the Python hosting integration

### Article abstract

Overview of the extension package

**Comment by aaronpowell** [comment]
@tommasodotNET Are you able to tackle this one?

**Comment by tommasodotNET** [comment]
Should we wait for [this](https://github.com/CommunityToolkit/Aspire/issues/221)?

**Comment by aaronpowell** [comment]
Nah, let's get what's shipped documented and add to it as needed
