### ISSUE TITLE
[CSS]: Breadcrumb link is not updated when navigating

### ISSUE THREAD

**Issue by HugoDurana** [dotnet/docs-aspire#2099]
### Article title

All Documents

### Article URL

All URLS

### Description

As we visit the documentation, the breadcrumb at the top of the page does not reflect the structure of the TOC, or at least the navigation steps taken to reach said article.

**Comment by IEvangelist** [comment]
We're actually restricted with how breadcrumbs work. While I hear your concern, and I do agree with it - we cannot change this. The platform requires that hub and landing pages serve as an index for all breadcrumb nodes. This doc set only has a single hub and single landing page. Hence, we can only have `.NET / .NET Aspire`. I could try to see about perhaps at least trying to follow the breadcrumb with overviews, I'll give that a try - but if it introduces build issues, I'll have to pull it out.

**Comment by IEvangelist** [comment]
Yeah, I just tried this and it doesn't work. 😾
