### ISSUE TITLE
Walkthrough of CI/CD with GitHub Actions and Azure DevOps for AZD and .NET Aspire

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#21]
We need an article that covers the outer loop for AZD and .NET Aspire. We should be sure to cover off failing the build if azd infra synth generates alternative content.

**Comment by jerone** [comment]
I found the article with [GitHub Actions](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions), but I cannot find an article using Azure DevOps Pipelines...
