### ISSUE TITLE
[CSS]: .NET Aspire GitHub Repository link should be under references

### ISSUE THREAD

**Issue by HugoDurana** [dotnet/docs-aspire#2101]
### Article title

N/A

### Article URL

N/A

### Description

As of this moment, under the troubleshooting section, there is a link to the .NET Aspire GitHub repository. This link would be better placed under either Reference or resources - I can understand the logic behind putting it under troubleshooting, nonetheless I see this more as reference material than rather troubleshooting material.

**Comment by IEvangelist** [comment]
We usually reserve `References` for API docs or things that serve as reference material. We do have the .NET Aspire Repository linked to on the Hub page and in the TOC under the `Resources` node. I'm going to close this:

![Image](https://github.com/user-attachments/assets/33d9dda3-070c-4ab3-82db-2dc18eb839d3)
