### ISSUE TITLE
Update .NET Aspire dashboard docs.

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs-aspire#214]
Update the .NET Aspire Dashboard article:

- Resources vs Project/Container/Executable
- Misc updates
- Recapture screenshots

Here are the changes to the dashboard for `preview.2`:

- Combined Resources View https://github.com/dotnet/aspire/pull/987
- Combine console logs pages https://github.com/dotnet/aspire/pull/1034
- Add command & args to container source column https://github.com/dotnet/aspire/pull/1205
- Add log category name to structured logs https://github.com/dotnet/aspire/pull/1214
- Use UID throughout dashboard UI for disambiguation https://github.com/dotnet/aspire/pull/1229
- Resolve outgoing peer browserlink call in trace UI https://github.com/dotnet/aspire/pull/1061
- Tracing UI displays resource name for outgoing resources https://github.com/dotnet/aspire/pull/1040

**Comment by alistairmatthews** [comment]
PR #224 should fix this issue.
