### ISSUE TITLE
.NET Aspire networking documentation

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#232]
We need a section in the TOC that covers off the interaction between apps and containers running locally in Aspire and the Traefik proxies that DCP manages. We don't necessarily need to mention DCP or traefik as they are mostly implementation details from an Aspire perspective but we need to make it clear that when a service binding is added either implicitly (via launch profiles) or explicitly via a manually added service binding that Aspire will launch a Traefik proxy on that port, and the executable, project or container will be assigned another port.

In the case of Projects we automatically inject the appropriate ASPNETCORE_URLS environment variables. For containers we randomly assign the ports using the magic of Docker. For executables it requires some integration where we will optionally inject an environment variable with the port assigned for each service binding. This means that the executable will need to use that variable to figure out what port to bind to locally in order to avoid conflicts.

Networking isn't an inner loop only consideration. We probably need pages to cover various deployment scenarios and considerations and limitations of each target environment. There is not always a 1:1 mapping between what we do locally, and what gets deployed to the target environment.

---
[Associated WorkItem - 198655](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198655)

**Comment by davidfowl** [comment]
I would focus on how the app code relates to what happens:
- How launch profiles into service bindings
- Service bindings have 2 addresses, the port the application listens on and the port that clients connect to
- How service bindings work with containers (there's an extra container port)

Then we need a diagram:

![image](https://github.com/dotnet/docs-aspire/assets/95136/2d850ce4-43f7-4813-83eb-527b145f3a3d)

**Comment by IEvangelist** [comment]
This is great, I was curious how a lot of these things worked, and visuals were something I thought would go a long way with communicating these core concepts. The `WithServiceBindings` API needs more clarity about how/when/why to use it. Perhaps a diagram that shows which port is which? 🤓

**Comment by davidfowl** [comment]
## LaunchSettings.json

When you call AddProject, the apphost looks for `Properties/launchSettings.json` to determine the default set of service bindings. The app host selects a specific launch profile using the following rules:

1. An explicit `WithLaunchProfile` call on the `IResourceBuilder<ProjectResource>`
2. via the `DOTNET_LAUNCH_PROFILE` environment variable (visual studio sets this I believe)
3. Picking the first launch profile defined in `launchSettings.json`

Consider the following profile:

```JSON
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:64225",
      "sslPort": 44368
    }
  },
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5066",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "https://localhost:7239;http://localhost:5066",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

### Example

```C#
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject<Projects.WebApplication2>("frontend")
       .WithLaunchProfile("https");

builder.Build().Run();
```

This will select the **https** launch profile from `launchSettings.json`. The `applicationUrl` of that launch profile will be used to create a service binding for this project. This is the equivalent of:

```C#
builder.AddProject<Projects.WebApplication2>("frontend")
       .WithServiceBinding(hostPort: 5066, scheme: "http")
       .WithServiceBinding(hostPort: 7239, scheme: "https");
```

## What happens if there's no launchSettings.json?

If there's no `launchSettings.json` or there's no launch profile there will be no bindings by default.

**Comment by davidfowl** [comment]
## Ports and Proxies!

When defining a service binding, the host port is *always* given to the proxy that sits in front of the service:

```C#
builder.AddProject<Projects.WebApplication2>("frontend")
       .WithServiceBinding(hostPort: 5066, scheme: "http")
```

There will be 2 ports defined:
- The proxy port 5066
- The port that the underlying service will be bound to (a randomly chosen port)

![image](https://github.com/dotnet/docs-aspire/assets/95136/8f59d17d-f715-4b81-9a9d-8518b6981ab2)

The underlying service is fed this port via ASPNETCORE_URLS for project resources. Other resources can get access to this port by specifying an environment variable on the service binding:

```C#
﻿var builder = DistributedApplication.CreateBuilder(args);

builder.AddNpmApp("frontend", "../NodeFrontend", "watch")
    .WithServiceBinding(hostPort: 5067, scheme: "http", env: "PORT");

builder.Build().Run();
```

The above code will make the random port available in the PORT env variable.

![image](https://github.com/dotnet/docs-aspire/assets/95136/f0795a24-fb9a-4fff-83c8-13a4acfb7191)

**Comment by davidfowl** [comment]
cc @karolz-ms

**Comment by mitchdenny** [comment]
This is great!

**Comment by davidfowl** [comment]
Need content for containers.

**Comment by IEvangelist** [comment]
This is awesome, thank you very much @davidfowl! How would I use the `WithServiceBindings` if I know that my `ExecutableResource` is set to communicate over a specific port, for example:

| JS app | Defaults |
|--|--|
| Angular | `localhost:4200` |
| React | `localhost:3000` |
| Vue | `localhost:5173` |

What would the call to `WithServiceBindings` look like for each, as I couldn't get this to work as I imagined it would.

**Comment by davidfowl** [comment]
When you're running an executable, the orchestrator wants to control the port you're listening on, so you have to be given a port.

https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project

```C#
builder.AddNodeApp("frontend", "../react/app.js")
       .WithServiceBinding(scheme: "http", env: "PORT");
```

**Comment by davidfowl** [comment]
If the port is specified it means replicas won't work on a single machine. To get full networking isolation you'd need to run in a container. There you can specify the container port.

**Comment by davidfowl** [comment]
```C#
builder.AddContainer("frontend", "mcr.microsoft.com/dotnet/samples", "aspnetapp")
       .WithServiceBinding(hostPort: 8000, containerPort: 8080, scheme: "http");
```

![image](https://github.com/dotnet/docs-aspire/assets/95136/c5db5f63-ed7f-40e9-846b-eb5bf01e93fc)

**Comment by davidfowl** [comment]
For the container port section it's also worth calling out what is shown in the docker desktop tooling:

<img width="1085" alt="image" src="https://github.com/dotnet/docs-aspire/assets/95136/c5394e76-76bb-4310-b5d6-4cd6388b9f16">

The "none" in endpoints for the cache service is a bug (https://github.com/dotnet/aspire/issues/1431 and https://github.com/dotnet/aspire/issues/1489).

Here's the proxy endpoint specified in the env variable:

<img width="1022" alt="image" src="https://github.com/dotnet/docs-aspire/assets/95136/c318c3cc-48fc-4621-8d3f-229fd6c47a53">

**Comment by davidfowl** [comment]
One thing I missed was the fact that `WithReference` always uses the **proxy endpoint** puts that in the environment variable.

**Comment by karolz-ms** [comment]
Just a reminder that `WithServiceBinding` has been renamed to `WithEndpoint`

**Comment by rolfik-mycronic** [comment]
Thank You for clarification.
We have also a legacy java http service running on specific port on Windows.
How can I specify its port in `WithServiceBinding` if it is not running in a container?

**Comment by davidfowl** [comment]
You cant use WithServiceBinding currently. That always starts a proxy.

Thats currently the by way a url will show up. This is a feature request. We’ll also need to block replicas for these services

**Comment by davidfowl** [comment]
Filed https://github.com/dotnet/aspire/issues/1637 @rolfik-mycronic
