### ISSUE TITLE
Should Include the Command to Take Down Resources

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/docs-aspire#267]
### Type of issue

Missing information

### Description

A code block is shown to create the resources shown in the messaging tutorial via the azure cli or cloudshell

az group create -n <your-resource-group-name> -location eastus
az servicebus namespace create -g <your-resource-group-name> --name <your-namespace-name> --location eastus
az servicebus topic create --g <your-resource-group-name> --namespace-name <your-namespace-name> --name notifications
az servicebus topic subscription create --g <your-resource-group-name> --namespace-name <your-namespace-name> --topic-name notifications --name mobile

I think a small codeblock section at the end of the page that gives the commands to remove the cloud resources would help people are just trying to create the resources quickly for this one-time tutorial.  I am thinking something along the lines of this.

```ps
# Define variables
RESOURCE_GROUP="<your-resource-group-name>"
NAMESPACE="<your-namespace-name>"

# Delete Service Bus topic subscription
az servicebus topic subscription delete --resource-group $RESOURCE_GROUP --namespace-name $NAMESPACE --topic-name notifications --name mobile

# Delete Service Bus topic
az servicebus topic delete --resource-group $RESOURCE_GROUP --namespace-name $NAMESPACE --name notifications

# Delete Service Bus namespace
az servicebus namespace delete --resource-group $RESOURCE_GROUP --name $NAMESPACE

# Delete the resource group
az group delete --name $RESOURCE_GROUP --yes --no-wait

```

Just something so that I can easily remove the resources without having to go and google the commands to remove them or go into the azure portal and manually remove them. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?tabs=passwordless

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/messaging/messaging-components.md

### Document Version Independent Id

1b6029c0-3592-34d4-1218-1db530b4ce28

### Article author

@IEvangelist

**Comment by alexwolfmsft** [comment]
Thank you, resolved with https://github.com/dotnet/docs-aspire/pull/372
