### ISSUE TITLE
"APIs for adding and expressing resources" has links to no longer existing methods

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs-aspire#273]
### Type of issue

Outdated article

### Description

These `Add...Connection` methods no longer exist:

![image](https://github.com/dotnet/docs-aspire/assets/8291187/6d19383c-54c6-4e0f-a58e-430b6900bf76)

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/fundamentals/app-host-overview.md

### Document Version Independent Id

2dc8f42f-e9ca-fbe1-bef9-af4b4f20dc7d

### Article author

@IEvangelist

**Comment by IEvangelist** [comment]
This was addressed in #274
