### ISSUE TITLE
Tutorial Restructuring to Illustrate Convenience of Aspire

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/docs-aspire#278]
### Type of issue

Other (describe below)

### Description

# Summary

I've noticed that the instructions suggest adding the Redis connection string to the appsettings.json file in the ui and api project. While this approach works, I believe it's unnecessary. Instead, it would be more intuitive to first show the "Configure the App Host project" Section and then proceed to the 'Configure the API with Distributed Caching' section, omitting the connection string part altogether.

My suggestion to rearrange the content in this order stems from the opportunity to demonstrate an example of 'Implicit Service Discovery by Reference'. This would also showcase the simplicity of setting up Redis with Aspire.

### Prerequisites
...

### Create the project
...

### Configure the App Host project
...
- opportunity to add to this section and mention that implicit service reference makes it so that we no longer need connection strings and only it's service name.

### Configure the UI with output caching
... (omit connection string)
- bring up the "cache" service name again above this code section 
<code> builder.AddRedisDistributedCache("cache"); </code>

### Configure the API with distributed caching
... (omit connection string)
- bring up the "cache" service name again above this code section 
<code> builder.AddRedisDistributedCache("cache"); </code>

### Test the app locally
...

### Explain Some of the Magic of Aspire (New Section)
- simply state that the ui and api are obtaining the connection strings via implicit reference (refer to app host program.cs file)
- then show a screenshot of the the environment variables for the ui and api in the dashboard (which will be in something along the lines of "connectionStrings__cache")

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/caching/caching-components

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/caching/caching-components.md

### Document Version Independent Id

76ef3cc2-e49d-d8da-b6d0-57fac1e9c332

### Article author

@IEvangelist

**Comment by IEvangelist** [comment]
I'm not opposed to that, but we should at least mention that the connection string option is available to the readers. Would you be interested in creating a pull request @josephaw1022? If so, I could assign this issue to you and review the corresponding PR - just let me know.

**Comment by josephaw1022** [comment]
@IEvangelist I agree to your first point and absolutely

**Comment by josephaw1022** [comment]
@IEvangelist  I noticed the usage of _appsettings.json and not appsettings.json. Is that on purpose or was that just a typo that I can fix?

**Comment by josephaw1022** [comment]
I think I figured it out. I am guessing typo from this spike repo that I just made. 

https://github.com/josephaw1022/ConnectionStringAspireSpike

**Comment by IEvangelist** [comment]
> @IEvangelist I noticed the usage of _appsettings.json and not appsettings.json. Is that on purpose or was that just a typo that I can fix?

Yeah, that's a typo. All references to files or directories should be styled as italics.
