### ISSUE TITLE
'IDistributedApplicationBuilder' does not contain a definition for 'AddAzureCosmosDB

### ISSUE THREAD

**Issue by dcaponi** [dotnet/docs-aspire#311]
### Type of issue

Code doesn't work

### Description

Following instructions [here](https://learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-entity-framework-component?tabs=dotnet-cli#orchestration) for orchestration I get the error:

```sh
error CS1061: 'IDistributedApplicationBuilder' does not contain a definition for 'AddAzureCosmosDB' and no accessible extension method 'AddAzureCosmosDB' accepting a first argument of type 'IDistributedApplicationBuilder' could be found (are you missing a using directive or an assembly reference?) 
```

I have the following packages installed
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="8.0.0-preview.2.23619.3" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.Cosmos" Version="8.0.0-preview.2.23619.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TodoApi\TodoApi.csproj" />
  </ItemGroup>

</Project>
```

and my AppHost looks like:

```c#
using Aspire.Microsoft.EntityFrameworkCore.Cosmos;

var builder = DistributedApplication.CreateBuilder(args);

var cosmosdbService = builder
    .AddAzureCosmosDB("cosmosdb")
    .AddDatabase("todos");
                            
builder.AddProject<Projects.TodoApi>("todoapi")
    .WithReference(cosmosdbService); ;

builder.Build().Run();
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/database/azure-cosmos-db-entity-framework-component?tabs=dotnet-cli

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/database/azure-cosmos-db-entity-framework-component.md

### Document Version Independent Id

8b585800-8c7b-df72-3125-2776e1b1375e

### Article author

@IEvangelist

---
[Associated WorkItem - 202718](https://dev.azure.com/msft-skilling/Content/_workitems/edit/202718)

**Comment by davidfowl** [comment]
Yes the docs need to be updated. This overload is in Aspire.Hosting.Azure. The apphost shouldn’t reference “Aspire.Microsoft.EntityFrameworkCore.Cosmos”

**Comment by dcaponi** [comment]
Rad, thank you!

`dotnet add package Aspire.Hosting.Azure` 

In AppHost => `var cosmosdbService = builder.AddAzureCosmosDB("cosmosdb");`

In consuming service (in my case TodoApi) `builder.AddCosmosDbContext<TodoDbContext>("cosmosdb", "todos");
` where "cosmosdb" is the database and "todos" is the container

That gets the build going. Now its down to diagnosing connection issues which might be more of a me problem :)

**Comment by davidfowl** [comment]
When you call AddAzureCosmoseDb locally in development, did you specify the cosmos connection string (are you connecting to an existing resource?) ?

**Comment by dcaponi** [comment]
Yeah. I specify connection string in AppHost.appsettings.json like so
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Aspire.Hosting.Dcp": "Warning"
    }
  },
  "ConnectionStrings": {
    "cosmosdb": "AccountEndpoint=https://[redacted];"
  }
}

```
And it comes through when I run the aspire project (I can see it when I expand the TodoApi's environment variables in the UI. Its labeled `ConnectionStrings__cosmosdb`

In TodoAPI I specify the context like so

```c#
builder.AddCosmosDbContext<TodoDbContext>(
    "cosmosdb", 
    "todos", 
    settings => settings.ConnectionString = Environment.GetEnvironmentVariable("ConnectionStrings__cosmosdb")
);
```

I've also tried it without the `settings` lambda. Both lead to a 404. The resource exists in Azure and I have a database that I just call `cosmosdb` for now and a container called `todos`

DB context looks like this if it's helpful
```c#
public class TodoDbContext : DbContext 
{
    public TodoDbContext(DbContextOptions<TodoDbContext> options) : base(options)
    {}

    public DbSet<Todo> Todos {get; set;}

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.HasDefaultContainer("todos");
        builder.Entity<Todo>();
    }
}
```

**Comment by davidfowl** [comment]
This can be simplified:

```
builder.AddCosmosDbContext<TodoDbContext>("cosmosdb", "todos");
```

Do you need to run database creation logic in EF so that it works?

**Comment by dcaponi** [comment]
Right thats what I thought.

Not sure I follow. I tried `ctx.Database.EnsureCreated` but running that seems to 

A) create a new database in my cosmosdb instance called `todos` which is unexpected and
B) I get an error about needing to add 400 RU/s throughput. I'm on a free account so 1000 RU/s is the limit. Running `EnsureCreated()` seems to require 1400 for some reason
