### ISSUE TITLE
Document preview-to-preview upgrade steps

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs-aspire#341]
When upgrading a .NET Aspire app from a previous preview, there are a few steps that need to happen:

1. Install the new workload version
2. Update all Aspire PackageReferences (especially the `Aspire.Hosting` reference in the AppHost.csproj) to match the version of the workload you are updating to
3. Update any code that used APIs that were removed/changed to the new APIs

We should have an upgrade section in our docs that list these steps, and have a trouble shooting section for common mistakes, and what errors you see.

One example of having a mis-matched workload and `Aspire.Hosting` PackageReference version is: https://github.com/dotnet/aspire/issues/1944

cc @IEvangelist

**Comment by maryamariyan** [comment]
I hit this issue as well. Here's a breakdown of what happened and what I did:
- I realized I used VS installer to update the VS version, that updated the workload I believe
- confirmed that by checking the version listed using "dotnet workload list"
- updated the nuget package to preview3
- and it builds now.
- maybe could be noted that it would have built fine if the workload version was different
