### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by vRune4** [dotnet/docs-aspire#345]
### Type of issue

Missing information

### Description

https://github.com/Azure/login provides a lot of information on how to log in, including using OIDC.

So I have two questions that I'd like to see answered in the docs:

1. Is it possible to use the azure/login@v1 github action?
2. If not, I assume the federated credential has to look similar (you should provide same info as azure/login)

(That said, I am happy I found some github actions documentation at all!)

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/deployment/azure/aca-deployment-github-actions.md

### Document Version Independent Id

c4fd539b-5f60-2dd0-0bf1-d0a218b99427

### Article author

@IEvangelist

**Comment by vRune4** [comment]
Mostly because I have azure/login working in my existing pipeline. Will the federated credential have the same subject if I switch to azd login?

**Comment by IEvangelist** [comment]
Closing this as it appears to be a non-issue, more like a question that was answered. If I'm wrong, feel free to let me know and we can reopen this.
