### ISSUE TITLE
Potential documentation error (port number)

### ISSUE THREAD

**Issue by jonmikeli** [dotnet/docs-aspire#347]
### Type of issue

Other (describe below)

### Description

I am still new to Aspire but I have the feeling there is a mistake in the documentation.

Section : [link](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview?WT.mc_id=AZ-MVP-5004280#connection-string-and-endpoint-references)

Mistake:
services__myapp__0=http://_http.localhost:8034

instead of

services__myapp__0=http://_http.localhost:9043

Knowing that the port 9043 has been specified in the code of the example (see below), I would expect to find the same port number in the environment variables.

```csharp
var customContainer = builder.AddContainer("myapp", "mycustomcontainer")
                             .WithServiceBinding(containerPort: 9043, name: "endpoint");

var endpoint = customContainer.GetEndpoint("endpoint");

var apiservice = builder.AddProject<Projects.AspireApp_ApiService>("apiservice")
                        .WithReference(endpoint);
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/app-host-overview

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/fundamentals/app-host-overview.md

### Document Version Independent Id

2dc8f42f-e9ca-fbe1-bef9-af4b4f20dc7d

### Article author

@IEvangelist

---
[Associated WorkItem - 214647](https://dev.azure.com/msft-skilling/Content/_workitems/edit/214647)

**Comment by davidfowl** [comment]
What version of aspire are you using?

**Comment by IEvangelist** [comment]
Hi @jonmikeli - happy to look into this but need to know a bit more info to help. Can you provide the version of .NET Aspire you're using?

**Comment by jonmikeli** [comment]
Hi @davidfowl , @IEvangelist ,

Apologies @davidfowl. I missed your message.
Answering the question, at the time I reported the issue, I was using the preview2.

Just to be sure everything is clear, the issue was more related to documentation (not Aspire per se).
Not sure the version would be relevant here but feel free to correct me.

**Comment by IEvangelist** [comment]
I see the issue, fixing it now. Thanks for reporting this.
