### ISSUE TITLE
For Aspire preview.3, we should document the issues that Aspire CLI and VS customers will face with .NET SDK 9.0 installed and provide workarounds

### ISSUE THREAD

**Issue by balachir** [dotnet/docs-aspire#366]
For the aspire Setup and tooling documentation (i.e. [this document](https://learn.microsoft.com/en-us/dotnet/aspire/setup-tooling?tabs=visual-studio), when customers who are already using Aspire install .NET SDK 9.0 Preview 1, this can break their Aspire workload installation / experience. We have a couple of known issues around this - see https://github.com/dotnet/aspire/issues/1951 and https://github.com/dotnet/aspire/issues/2186. 

We should clearly document the issues that Aspire customers will run into when they install .NET SDK 9.0 Preview 1, and provide them with the appropriate workarounds.

cc: @IEvangelist

**Comment by IEvangelist** [comment]
Closed by #359
