### ISSUE TITLE
Update the .NET Aspire dashboard page to reflect `preview-3` changes

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs-aspire#367]
We need updated screen captures:

- [ ] Trace length radial icon
- [ ] Resource details view
- [ ] Telemetry improvements
  - Metrics filter UI
  - Histogram metrics count
  - Span events
 
@alistairmatthews could you take this one please?

**Comment by alistairmatthews** [comment]
@IEvangelist Yes! On it now.

**Comment by alistairmatthews** [comment]
PR #399 should fix all these. I've also revised some other screenshots that had changed.
