### ISSUE TITLE
Hosting support for CosmosDB documentation inconsistencies.

### ISSUE THREAD

**Issue by JamesLMiller** [dotnet/docs-aspire#392]
### Type of issue

Code doesn't work

## Hosting Support for CosmosDB

I would like to use the Aspire workflow for adding hosting support for my application, but after following the documentation listed, the code provided does not perform as expected. 

The first sentence states  _**To use Comos DB in your app host you can do the following:**_

```
var builder = DistributedApplication.CreateBuilder(args);

var db = builder.AddAzureCosmosDB("cosmos")
                .UseEmulator()
                .AddDatabase("db");

var app = builder.AddProject<Projects.MyApp("app");

```

I have created a test project called CosmosDBTest, and inside of my _**Program.cs**_ of my _**CosmosDBTest.AppHost**_  I have added the above code. 

I have added as dependencies to this project:

- **Aspire.Hosting( 8.0.0-preview.3.24105.21)**
- **Aspire.Hosting.Azure (8.0.0-preview.3.24105.21)**
- **Aspire.Microsoft.EntityFrameworkCore.Cosmos (8.0.0-preview.3.24105.21)**
- **Microsoft.EntityFrameworkCore.Cosmos (8.02)**

I have added the above code to my project, and this seems to work, but I am confused about the next statement after that block of code which reads: 

_**Inside the entrypoint for the application code you can wire up the Cosmos DB client using the following:**_

```
builder.AddAzureCosmosDB("db", static settings =>
{
    settings.IgnoreEmulatorCertificate = true;
});
```

To me, the _**entrypoint**_ is a little misleading here, because in my test app, that would be the **Program.cs** of my **_CosmosDBTest.Web_** project.

If I add this code here, I am met with the error:

_**WebApplicationBuilder does not contain a definition for AddAzureCosmosDB**_

This makes sense conceptually, but the only place the above snippet of code will seem to work would then be back in my AspireAppHost. Is this correct? 

Also, when you put the code back in the AppHost, you get a syntax error

```
builder.AddAzureCosmosDB("db", static settings **=>**
{
    settings.IgnoreEmulatorCertificate = true;
});
```

_**Cannot convert lambda expression to type 'string' because it is not a delegate type.**_ . Again this makes sense, but according to the documentation I would (maybe naively) expect that code to _**just work**_.

What I would expect to happen based on this documentation is that the container for the Cosmos Emulator would spin up in my AppHost and I would be able to connect to it and then write data to the emulator. 

As a side note, If I leave the _**IgnoreEmulatorCertificate**_ snippet out, I do see the cosmos container start up in my Aspire Dashboard, but I cannot connect to it. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-3

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/whats-new/preview-3.md

### Document Version Independent Id

46a1b04d-be87-71b4-577d-1e9f16a1744b

### Article author

@IEvangelist

**Comment by IEvangelist** [comment]
I've been working on an Azure Cosmos DB example that shows usage with the emulator, that will hopefully help others who encounter the same issue as you. In the meantime, know that there are two APIs with the same name (I know, not ideal as they mean slightly different things):

- From the app host, when you call [`AddAzureCosmosDB` you use this API](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.azurecosmosdbcloudapplicationbuilderextensions.addazurecosmosdb?view=dotnet-aspire-8.0#aspire-hosting-azurecosmosdbcloudapplicationbuilderextensions-addazurecosmosdb(aspire-hosting-idistributedapplicationbuilder-system-string-system-string)).
- From any consuming app, meaning anything that needs to use the `CosmosClient` you'll call [this `AddAzureCosmosDB` API](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.aspireazurecosmosdbextensions.addazurecosmosdb?view=dotnet-aspire-8.0#microsoft-extensions-hosting-aspireazurecosmosdbextensions-addazurecosmosdb(microsoft-extensions-hosting-ihostapplicationbuilder-system-string-system-action((aspire-microsoft-azure-cosmos-azurecosmosdbsettings))-system-action((microsoft-azure-cosmos-cosmosclientoptions)))).

With that in mind, your app host could add Azure Cosmos DB like this:

```cs
var builder = DistributedApplication.CreateBuilder(args);

var cosmos = builder.AddAzureCosmosDB("cosmos")
                    .UseEmulator()
                    .AddDatabase("db");

builder.AddProject<Projects.MyFrontend>("frontend")
       .WithReference(cosmos);
```

This requires the `Aspire.Hosting.Azure` NuGet package.

Then in your web app, where you're consuming Cosmos DB you'd do this:

```cs
var builder = WebApplication.CreateBuilder(args);

builder.AddAzureCosmosDB("db", static settings =>
{
    settings.IgnoreEmulatorCertificate = true;
});
```

This requires the `Aspire.Microsoft.Azure.Cosmos` NuGet package. Does that make sense?

**Comment by JamesLMiller** [comment]
Ok this is great information. Thank you! I have adjusted my NuGet package dependencies on my project now, and things seem to be working!
