### ISSUE TITLE
components-overview.md

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#4]
In ```components-overview.md``` we don't really mention the orchestrator side of what someone needs to do when they set up Postgres within a service. We should probably explain both sides of the equation in more detail.

---
[Associated WorkItem - 189985](https://dev.azure.com/msft-skilling/Content/_workitems/edit/189985)

**Comment by IEvangelist** [comment]
Hi @mitchdenny and @eerhardt - what should be said about the orchestrator side?

**Comment by eerhardt** [comment]
My thinking is that we'd have the corresponding AppHost code that makes a PostgreSQL database with the same name that is passed into `AddNpgsqlDataSource` and that the connection string is passed from the AppHost to the service project.

![image](https://github.com/dotnet/docs-aspire/assets/8291187/3639b6df-5b1e-4cfb-9dca-014267109c37)

Not hard-coding the connection string in the appsettings.json file.  (We can document the appsettings.json location later in the doc). But this should be talking about the AppHost side as well.
