### ISSUE TITLE
Module 2: Create a .NET Aspire application

### ISSUE THREAD

**Issue by CamSoper** [dotnet/docs-aspire#417]
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/create-aspire-applications/?branch=pr-en-us-42327)

PR: https://github.com/MicrosoftDocs/learn-pr/pull/42327

---
[Associated WorkItem - 215927](https://dev.azure.com/msft-skilling/Content/_workitems/edit/215927)

**Comment by PhilStollery** [comment]
@CamSoper and @IEvangelist I've addressed all feedback. Updated yaml and filenames. Can we create an official MS repo for my sample code https://github.com/PhilStollery/aspire-starter?

I tried to fix my PR my updating my branch with updates from main - so have screwed the PR. Should I delete and create a new PR?

**Comment by CamSoper** [comment]
> I tried to fix my PR my updating my branch with updates from main - so have $*@^@@& the PR. Should I delete and create a new PR?

Sure, that's the easiest way.

Here's a repo for the sample. You and @alistairmatthews should have write access.  https://github.com/MicrosoftDocs/mslearn-aspire-starter

LOL @IEvangelist's profanity filter 🤣 @IEvangelist is the fun police! 🚓🚨

**Comment by PhilStollery** [comment]
https://github.com/MicrosoftDocs/learn-pr/pull/42973

**Comment by CamSoper** [comment]
@PhilStollery ping me here when you do, my GitHub inbox is really noisy and I miss PRs sometimes

**Comment by bradygaster** [comment]
@alistairmatthews this staging link seems broken can you update it with the right one? or hit me here with it?

**Comment by alistairmatthews** [comment]
> [@alistairmatthews](https://github.com/alistairmatthews) this staging link seems broken can you update it with the right one? or hit me here with it?

@bradygaster - the new staging link is here: [Staging link](https://review.learn.microsoft.com/en-us/training/modules/create-aspire-applications/?branch=pr-en-us-43741)

I don't have permissions to edit the one above. :~(

**Comment by bradygaster** [comment]
Reviewed this one, left a few notes in teams to provide commentary as I'm not sure where to provide commentary in a pull request.

**Comment by alistairmatthews** [comment]
I've updated this module to preview 6. Just small changes and screenshots.

**Comment by alistairmatthews** [comment]
I've created a new PR for this: https://github.com/MicrosoftDocs/learn-pr/pull/44681
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/create-aspire-applications/?branch=pr-en-us-44681)
Module is ready to merge.

**Comment by alistairmatthews** [comment]
This is the latest PR, which fixes two small blockers: https://github.com/MicrosoftDocs/learn-pr/pull/44688
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/create-aspire-applications/?branch=pr-en-us-44688)
