### ISSUE TITLE
Refers to Visual Studio 2022 version 17.9 as a pre-requisite which isn't even out yet

### ISSUE THREAD

**Issue by mamift** [dotnet/docs-aspire#42]
### Type of issue

Typo

### Description

Hello, 

As of 14 Nov 2024, on this page: https://learn.microsoft.com/en-au/dotnet/aspire/get-started/quickstart-build-your-first-aspire-app?tabs=visual-studio it refers to *Visual Studio 2022 version 17.9 or higher (Optional)* as a pre-requisite, but the latest version of VS as of 14 Nov 2023 is 17.8, not 17.9.

It's under the Pre-requisite section: https://learn.microsoft.com/en-au/dotnet/aspire/get-started/quickstart-build-your-first-aspire-app?tabs=visual-studio#prerequisites

### Page URL

https://learn.microsoft.com/en-au/dotnet/aspire/get-started/quickstart-build-your-first-aspire-app?tabs=visual-studio

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/get-started/quickstart-build-your-first-aspire-app.md

### Document Version Independent Id

5af6bf54-9e3e-025f-e1ff-b2a550558f35

### Article author

IEvangelist

**Comment by IEvangelist** [comment]
Hi @mamift - thanks for posting the first .NET Aspire issue since going public! Much appreciated. This was fixed in #40. It's currently in Preview... I'm going to close this, as we'll publish changes tomorrow AM. Thank you
