### ISSUE TITLE
Update setup instructions for preview 4

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#423]
### Type of issue

Typo

### Description

- [ ] We need VS 17.10 preview.
- [ ] Screenshots need to be updated.
- [x] Also need to mention the extra templates we've added. (This was done in `preview-3`)

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/fundamentals/setup-tooling.md

### Document Version Independent Id

38acc47a-cbda-21f9-5364-2aa038b569a5

### Article author

@IEvangelist

---
[Associated WorkItem - 229454](https://dev.azure.com/msft-skilling/Content/_workitems/edit/229454)

**Comment by IEvangelist** [comment]
Hi @mitchdenny - I'm curious, do we need to say that Visual Studio 17.10 is required? The current language reads as 17.9 or higher, or are we just trying to push for the latest?

**Comment by mitchdenny** [comment]
Sorry for the delay. Yes we do
