### ISSUE TITLE
Add SQL-specific Azure deployment article.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#427]
At the end of this article:

https://learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-components#run-and-test-the-app-locally

We should link on to a new article which describes how to deploy a .NET Aspire application with a SQL database resource to Azure. We now no longer automatically provision an Azure Sql Server database resource, we will instead deploy a container. But we really want people to use Azure Sql Server so we need to teach them how to use the new API:

```csharp
builder.AddSqlServer("sql").PublishAsAzureSqlDatabase().AddDatabase(db);
```

**Comment by IEvangelist** [comment]
Hey, @alexwolfmsft - just curious, did you get a chance to start on this. Preview 4 drops tomorrow, not a big deal, just want to plan accordingly. If you do have a PR, target the `preview-4` branch. Unless obviously its already merged.

**Comment by IEvangelist** [comment]
Again, no worries. I was just curious. We just merged the `preview-4` branch.

**Comment by alexwolfmsft** [comment]
This captures the SQL deployment for preview 4

https://learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-component-deployment?tabs=visual-studio%2Cazure-sql
