### ISSUE TITLE
Make Azure Postgres Flexible Server specific deployment article.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#428]
At the end of this article:

https://learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-component?tabs=dotnet-cli

We should link on to a new article which describes how to deploy a .NET Aspire application with a Postgres database resource to Azure. We have a new API for this that generates Bicep that is used by AZD.

```csharp
builder.AddPostgres("pgsql").PublishAsAzurePostgresFlexibleServer().AddDatabase(db);
```

---
[Associated WorkItem - 238748](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238748)

**Comment by IEvangelist** [comment]
Hey @mitchdenny - is that code accurate?

I noticed that the `db` parameter in the `AddDatabase` call isn't a string, I'm assuming that's a typo.

**Comment by mitchdenny** [comment]
Yeah its a typo. Thanks!
