### ISSUE TITLE
Need complete rework on manifest article.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#432]
### Type of issue

Outdated article

### Description

In P4 we've eliminatd a lot of the abstract resource types such as `sqlserver.server.v0` in favor of just having the followin types:

- `container.v0`
- `dockerfile.v0`
- `project.v0`
- `parameter.v0` (new)
- `value.v0` (new)
- `azure.bicep.v0`

Other resource types have been removed. The thinking is that we use APIs such as `PublishAsX` to transform a resource that might have been deployed as a `container.v0` into a cloud specific resource which probably references a Bicep template (in the case of Azure) or some other IaC solution appropriate for the target environment.

This allows the developer to have more control over the shape of what is deployed and each deployment tool doesn't need to come up with its own customization mechanism outside of APIs that they were probably already building for C#.

The `parameter.v0` resource warrants more attention. Specifically, it allows the capture of values at deployment time that can then be injected into other resources. This is useful if you want to do something like deploy to production using a connection string for a resource.

The `value.v0` manifest type is typically used for child resources and doing some limited string interpolation (useful for appending database names on connection strings etc).

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/deployment/manifest-format.md

### Document Version Independent Id

22b9550d-dc9b-0b07-2193-b3a8fa4fca64

### Article author

@IEvangelist

---
[Associated WorkItem - 226911](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226911)

**Comment by IEvangelist** [comment]
Hey @mitchdenny - Is this the most accurate place to verify what's supported?

https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/apphost/generate.go#L356-L475
