### ISSUE TITLE
Typo: "http" vs "default" named endpoints in k8s example

### ISSUE THREAD

**Issue by DrEsteban** [dotnet/docs-aspire#44]
### Type of issue

Typo

### Description

https://learn.microsoft.com/en-us/dotnet/aspire/service-discovery/overview#named-endpoints-in-kubernetes-using-dns-srv

In the above section, the document says `a DNS SRV record being created for an endpoint named "http" and an endpoint named "dashboard"`. But the example _actually_ creates endpoints named `default` and `dashboard`. The rest of the section appears to refer to the correct name - this is the only typo.

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/service-discovery/overview

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/service-discovery/overview.md

### Document Version Independent Id

c250cb89-e0b4-c037-e4e0-edcec7c84eb8

### Article author

IEvangelist

**Comment by IEvangelist** [comment]
Hey @ReubenBond - could you please confirm that this is in fact an issue? I'm not familiar enough yet to know whether or not that was a typo or intentional.

**Comment by ReubenBond** [comment]
Yes, this is a typo, thanks for finding it.
