### ISSUE TITLE
Module 4: Use databases in a .NET Aspire app

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#443]
---
[Associated WorkItem - 226908](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226908)

**Comment by PhilStollery** [comment]
Don't seem to have the access rights to assign myself to this task. @bradygaster could you give myself and @alistairmatthews access?

**Comment by PhilStollery** [comment]
New PR: https://github.com/MicrosoftDocs/learn-pr/pull/43761

**Comment by alistairmatthews** [comment]
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/use-databases-dotnet-aspire-app/?branch=pr-en-us-43761)

**Comment by alistairmatthews** [comment]
[Final PR](https://github.com/MicrosoftDocs/learn-pr/pull/44923)
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/use-databases-dotnet-aspire-app/?branch=pr-en-us-44923)
