### ISSUE TITLE
Module 5: Improve performance with a cache in a .NET Aspire app

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#444]
---
[Associated WorkItem - 226909](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226909)

**Comment by alistairmatthews** [comment]
[Staging link]([https://review.learn.microsoft.com/en-us/training/modules/improve-performance-cache-aspire/?branch=pr-en-us-43430)

**Comment by alistairmatthews** [comment]
[Final PR](https://github.com/MicrosoftDocs/learn-pr/pull/44925)
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/improve-performance-cache-aspire/?branch=pr-en-us-44925)
