### ISSUE TITLE
Module 6: Send messages with RabbitMQ in a .NET Aspire app

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#445]
---
[Associated WorkItem - 239431](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239431)

**Comment by alistairmatthews** [comment]
Ready for review here: https://github.com/MicrosoftDocs/learn-pr/pull/43840

**Comment by alistairmatthews** [comment]
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/send-messages-rabbitmq-dotnet-aspire-app/?branch=pr-en-us-43840)
