### ISSUE TITLE
Module 7: Use Azure Storage in a .NET Aspire app

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#446]
---
[Associated WorkItem - 239429](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239429)

**Comment by alistairmatthews** [comment]
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/azure-storage-dotnet-aspire-app/?branch=pr-en-us-44181)

**Comment by alistairmatthews** [comment]
PR ready for review: https://github.com/MicrosoftDocs/learn-pr/pull/44181

**Comment by alistairmatthews** [comment]
New PR: https://github.com/MicrosoftDocs/learn-pr/pull/45106
Staging Link: https://review.learn.microsoft.com/en-us/training/modules/azure-storage-dotnet-aspire-app/?branch=pr-en-us-45106

**Comment by davidfowl** [comment]
The first thing I did was CTRL+F for RunAsEmulator and I didn't find it.

**Comment by alistairmatthews** [comment]
Thanks @davidfowl. I use it in the exercise but I haven't explained it in the text. I can add it to unit 2. Does anything else occur to you?

**Comment by CamSoper** [comment]
@alistairmatthews Let me know when you're ready for final review/publish on this one

**Comment by alistairmatthews** [comment]
I've added a section about the Azurite emulator. @bradygaster This one hasn't had a full technical review yet.

**Comment by alistairmatthews** [comment]
New PR for @bradygaster's review: https://github.com/MicrosoftDocs/learn-pr/pull/45356
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/azure-storage-dotnet-aspire-app/?branch=pr-en-us-45356)
