### ISSUE TITLE
[Components] New Seq component article

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs-aspire#484]
**Help us make content visible**

**Describe the new article**

We added a new `Aspire.Seq` component in preview5. See https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Seq and https://github.com/dotnet/aspire/pull/2426.

---
[Associated WorkItem - 238745](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238745)

**Comment by alexwolfmsft** [comment]
Closed with https://github.com/dotnet/docs-aspire/pull/584
