### ISSUE TITLE
Module 3: Use telemetry in a .NET Aspire app

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#487]
Learn how to use telemetry in a .NET Aspire app to log data and examine the behavior of a cloud-native application.

---
[Associated WorkItem - 239430](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239430)

**Comment by alistairmatthews** [comment]
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/use-telemetry-dotnet-aspire/?branch=pr-en-us-43393)

**Comment by bradygaster** [comment]
looked over this one, left a few comments in our team chat, but really thorough deep dive. curious what @samsp-msft says about this one if he gets a chance to review.

**Comment by samsp-msft** [comment]
Where is the best place to leave feedback.

**Comment by alistairmatthews** [comment]
Text and sample code upgraded to Preview 6.

**Comment by alistairmatthews** [comment]
I've tested the module successfully on GA and made small corrections. 
New PR: https://github.com/MicrosoftDocs/learn-pr/pull/44690
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/use-telemetry-dotnet-aspire/?branch=pr-en-us-44690)
