### ISSUE TITLE
Documentation and samples of Aspire + EF Core tooling

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs-aspire#488]
Follow on from https://github.com/dotnet/aspire/issues/398

There is an EF migrations playground app that can be used as a starting place for samples.

- [x] Sample - done here https://learn.microsoft.com/en-us/samples/dotnet/aspire-samples/aspire-efcore-migrations/
- [ ] Documentation

---
[Associated WorkItem - 232757](https://dev.azure.com/msft-skilling/Content/_workitems/edit/232757)

**Comment by JamesNK** [comment]
Documentation shouldn't be difficult to write. Can look to sample to see code required for various tasks, and steps required to generate and apply migrations.

**Comment by CamSoper** [comment]
FYI @IEvangelist and @joperezr -- I'm writing this but it's slipping into next week
