### ISSUE TITLE
[New article]: Landing page for diagnostic codes

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#521]
### Proposed topic or title

.NET Aspire Code Analysis Diagnostics

### Reason for the article

Proposed URL: https://learn.microsoft.com/dotnet/aspire/diagnostics/overview

This will be redirected to from diagnostic codes like this:

```csharp
[Experimental("ASPIRE0001", UrlFormat = "https://aka.ms/dotnet/aspire/diagnostics#{0}")]
```

There needs to be an anchor on the page in the form ASPIRE0001 for the example above. The aspire repo is using an aka.ms link so we can move this page around if we need to.

This change is being introduced as part of this PR:

https://github.com/dotnet/aspire/pull/2950

For ASPIRE0001 specifically we want to call out that the particular method or type being used contains experimental features. The code would probably be used for anything we deem as being experimental, but we might update content to specific experimental feature documentation which changes over time.

### Article abstract

This article contains details on diagnostic codes produced by .NET Aspire.

### Relevant searches

ASPIRE0001
CDK

---
[Associated WorkItem - 236523](https://dev.azure.com/msft-skilling/Content/_workitems/edit/236523)

**Comment by IEvangelist** [comment]
Are there plans to differentiate the diagnostic ID per API? If not, they're all going to navigate to the same heading which isn't really helpful.

**Comment by mitchdenny** [comment]
There will be other diagnostic IDs in the future for different things. For now however we just have that one for usage of overloads that expose CDK types.

Post GA I'm pretty sure we'll have some diagnostic codes and code fixers for pushing people to newer approaches for deployment.
