### ISSUE TITLE
[New article]: Document AddBicepTemplate / azd Magic

### ISSUE THREAD

**Issue by rudiv** [dotnet/docs-aspire#522]
### Proposed topic or title

Deploying Custom Bicep Files

### Location in table of contents.

Deployment/Azure

### Reason for the article

Outside of the Release Notes, there is no mention of `AddBicepTemplate` (which is super useful, thank you!) anywhere in the documentation as far as I can see.

Furthermore, there is magic contained within azd (my current understanding) that wires up certain parameters for custom bicep that aren't otherwise available.

For example, a `principalId` parameter is magically wired up to `resources.outputs.MANAGED_IDENTITY_PRINCIPAL_ID` which is great, but the only way for me to actually discover this was by creating a Key Vault, generating the manifest and essentially working out that azd magically did this. Whilst the Release Notes state that you can use "principalId" as a parameter, it's not really clear that this will be automatic given that `WithParameter(..)` doesn't require any arguments. My first attempt was at using `.WithParameter("managedIdentityId", "{resources.outputs.MANAGED_IDENTITY_PRINCIPAL_ID}")` (which appears that it should work given the formatting, but azd throws up not knowing was resources is, as it hasn't create it at that point).

Obviously `principalId` is just one example, but I'm going to guess there are more magical variables that I'm not aware of that are wired up in this way.

### Article abstract

Aspire Preview 4 added support for `AddBicepTemplate`.

You are able to provide parameters through a number of methods:

1. Via environment variables starting with AZURE_ followed by the name of the parameter, converted from camel case to upper-snake case.
2. By referencing the output of another Bicep Template using `otherBicepTemplate.GetOutput("outputName")`.
3. By using known parameter names (such as `AzureBicepResource.KnownParameters.PrincipalId`) to wire to automatically created resources from an Aspire deployment.

### Relevant searches

AddBicepTemplate
Bicep Template
Aspire Bicep Template Parameters

---
[Associated WorkItem - 263588](https://dev.azure.com/msft-skilling/Content/_workitems/edit/263588)

**Comment by IEvangelist** [comment]
Hi @rudiv - please have a look at #1060. Let me know what you think.

**Comment by rudiv** [comment]
Looks good to me! Great job 👍
