### ISSUE TITLE
Modify Aspire tooling/setup docs to have specific section on container runtime support

### ISSUE THREAD

**Issue by timheuer** [dotnet/docs-aspire#537]
### Describe the issue or suggestion

Since we support Docker and Podman container runtimes, we should modify https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio#install-net-aspire to:

- [ ] Note that Docker or Podman are the requirements for container runtime
- [ ] A specific linkable section/remark for container runtime that notes any env variables that can be set to force use Podman or otherwise <-- this would be fwlinked in product to missing runtime information

---
[Associated WorkItem - 236522](https://dev.azure.com/msft-skilling/Content/_workitems/edit/236522)

**Comment by IEvangelist** [comment]
It's easy to add the details about Docker or Podman, but I need a bit of clarification on the linkable section. Are you just in need of a section that talks about if you're using Podman, how to set it as an alias to docker?

**Comment by timheuer** [comment]
> @timheuer - It's easy to add the details about Docker or Podman, but I need a bit of clarification on the linkable section. Are you just in need of a section that talks about if you're using Podman, how to set it as an alias to docker?

Yes I was thinking it isn't enough to say 'both are supported' without a little explanation of how to ensure enable Podman.  There is an environment variable I thought we use. `DOTNET_ASPIRE_CONTAINER_RUNTIME=podman` I thought

**Comment by davidfowl** [comment]
The environment variable is to allow choosing the runtime when both are available. We currently prefer docker.

**Comment by IEvangelist** [comment]
The Podman docs talk about an alias, `alias docker=podman` is this something we should mention?

**Comment by davidfowl** [comment]
I don't think so. But we can generally point to their docs.

@karolz-ms @danegsta for their take.
