### ISSUE TITLE
Modify VS tooling section of setup for Aspire

### ISSUE THREAD

**Issue by timheuer** [dotnet/docs-aspire#538]
### Describe the issue or suggestion

RE: https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio#add-a-component

We've split the hosting packages and app components in latest VS experiences, should call them out differently here as "components" in apphost was causing confusion on what packages should be added there.	

---
[Associated WorkItem - 238744](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238744)

**Comment by IEvangelist** [comment]
Hi again @timheuer - is this for preview-5 or just with the latest VS bits?

**Comment by timheuer** [comment]
The VS will sync with Preview.5 release
