### ISSUE TITLE
[Health Checks] Document security considerations of health checks endpoints

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/docs-aspire#539]
The ServiceDefaults templates are being updated to only add the health checks endpoints in development environments and have a comment saying that details in the [Aspire health checks docs](https://learn.microsoft.com/dotnet/aspire/fundamentals/health-checks) should be reviewed before enabling them in non-development environments.

We should update the health checks docs to discuss protecting health checks using routing features like host filtering and/or authorization ([existing ASP.NET Core docs on this](https://learn.microsoft.com/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0#use-health-checks-routing)) as well as how to configure the health checks endpoints to use [request timeouts](https://learn.microsoft.com/aspnet/core/performance/timeouts?view=aspnetcore-8.0) and [output caching](https://learn.microsoft.com/aspnet/core/performance/caching/output?view=aspnetcore-8.0). We're going to add a sample of how to configure health checks endpoints with request timeouts and output caching in the Aspire samples repo (see https://github.com/dotnet/aspire-samples/issues/158).

---
[Associated WorkItem - 238743](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238743)

**Comment by IEvangelist** [comment]
To confirm, this is a `preview-5` change, right?

**Comment by DamianEdwards** [comment]
Correct
