### ISSUE TITLE
Add more deployment scenarios / details

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/docs-aspire#546]
### Describe the issue or suggestion

We are making changes to the [.NET Cloud page ](https://dotnet.microsoft.com/en-us/apps/cloud) to highlight Aspire come GA. One section will talk about deploying with Aspire and since there isn't enough room on the marketing page to cover the nuances of deployment, we are going to link to this doc for more details. 

#### Request 
- [ ] Update [Aspire Deployment page](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/overview) to include information on how to deploy to Kubernetes using [Aspirate](https://github.com/prom3theu5/aspirational-manifests)
- [ ] Update [Aspire Deployment page](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/overview) to include information on how to deploy to Kubernetes using kube manifests. 

@IEvangelist could you please add the Preview-5 label when you get a chance? Are there any other docs worth updating given these requested changes? 
@bradygaster 

---
[Associated WorkItem - 238742](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238742)

**Comment by IEvangelist** [comment]
We had an entire article dedicated to Aspirate - we removed it because it was changing so frequently. We could probably restore that page, or at least parts of it. Tagging @davidfowl for visibility.

**Comment by claudiaregio** [comment]
@IEvangelist @bradygaster I've updated the issue to request addition of how to deploy to Kubernetes using kube manifests in this issue - the team hasn't had a chance to try Aspir8 and we don't want folks to think it's the only option/fully supported at this time.
