### ISSUE TITLE
Updates to service defaults article

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#549]
We need to augment the Service Defaults (SD for short from here on out in this issue) article to document how folks could roll their own custom SD project. Specifically useful for supporting projects like the Worker, which uses the Worker SDK instead of the Web SDK, or console or executable projects, which don't have access to the ASP.NET Core libraries (nor would there be any need to add those to these style of projects via add-refs). 

There's a sample in the `aspire-samples` repo [here](https://github.com/dotnet/aspire-samples/tree/main/samples/ClientAppsIntegration) demonstrating a solution with multiple SD projects. Some things to point out when looking at this sample: 

- The [app defaults](https://github.com/dotnet/aspire-samples/tree/main/samples/ClientAppsIntegration/ClientAppsIntegration.AppDefaults) project avoids referencing ASP.NET Core
- The [service defaults](https://github.com/dotnet/aspire-samples/tree/main/samples/ClientAppsIntegration/ClientAppsIntegration.ServiceDefaults) project is more like the one we drop in for File -> New Aspire project creations, referencing ASP.NET Core
- The service defaults project is marked with the [IsAspireSharedProject](https://github.com/dotnet/aspire-samples/blob/main/samples/ClientAppsIntegration/ClientAppsIntegration.ServiceDefaults/ClientAppsIntegration.ServiceDefaults.csproj#L8) property. 

In our article update, we should tweak the code view of the SD csproj so that we have a tab view. One tab should show an "aspnet core-dependent" Service Defaults project. The other tab should show the "aspnet core-independent" version. This way people have copyable source in the docs for either scenario. We need to take care in the non-aspnetcore one to also include the `IsAspireSharedProject` property. This property could be used by developers to identify multiple options for the SD project they want projects to use. We'll need to support this so non-aspnetcore customers have guidance on how to build their own custom SD projects. 

---
[Associated WorkItem - 238738](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238738)

**Comment by IEvangelist** [comment]
> There's a sample in the aspire-samples repo [here](https://github.com/dotnet/aspire-samples/tree/main/samples/ClientAppsIntegration) demonstrating a solution with multiple SD projects.

I only see a single SD project in this sample. And the `AppDefaults` project isn't marked with `IsAspireSharedProject`.

If we're tweaking the article to show tabs, are we planning on introducing a new .NET Aspire template for `AppDefaults`? Or something like that, which would avoid the `FrameworkReference`?

**Comment by bradygaster** [comment]
We aren't planning at this time on adding a non-aspnetcore dependent service defaults project template. The doc is more to inform folks that it's possible should they need to do it. Whilst I don't mind the idea of a second template, I _really_ prefer the stance of showing folks what they could do. 

As to the `IsAspuireSharedProject`, we're thinking of changing the name to `IsAspireDefaultsProject`, but that's not yet locked. I'll update this issue once it is. And, we are working on supporting multiple defaults projects in the tooling experience.

**Comment by bradygaster** [comment]
@BillHiebert and @phenning - if/when the property name changes, please make sure to have me or one of us update this so @IEvangelist knows what to call it in the docs.
