### ISSUE TITLE
Article for ASPIRE_ALLOW_UNSECURED_TRANSPORT

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#551]
### Proposed topic or title

Allow Unsecured Transport

### Reason for the article

In .NET Aspire P5 we are making a change so that the AppHost will crash if an `applicationUrl` is using a non-TLS transprot (http). This change is in this PR and will be merged and backported to the P5 branch soon.

https://github.com/dotnet/aspire/pull/3177

This change includes a aka.ms link https://aka.ms/dotnet/aspire/allowunsecuredtransport which currently points to a non-existent page :https://learn.microsoft.com/dotnet/aspire/troubleshooting/allowunsecuredtransport

We would like this article to exist as a landing page for information about this error.

### Article abstract

See above.

---
[Associated WorkItem - 238740](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238740)

**Comment by mitchdenny** [comment]
@IEvangelist we might need an index page of all the various environment variables that matter in Aspire as well. Thoughts?

**Comment by IEvangelist** [comment]
See https://github.com/dotnet/aspire/issues/3250#issuecomment-2025220810
