### ISSUE TITLE
[New article]: Local Azure Provisioning Article

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#556]
### Proposed topic or title

Provisioning resources in Azure for local development

### Location in table of contents.

Deployment / Azure / X

### Reason for the article

In .NET Aspire P5 we've really boosted our support for provisioning Azure resources to support local development. This is especially useful where there isn't a good local analogue for the cloud resource (e.g. Azure Open AI/ServiceBus etc).

When configuration values are not present to support this feature (when activated) we have an aka.ms link: [dotnet/aspire/azure/provisioning](https://aka.ms/dotnet/aspire/azure/provisioning)

This currently points to: https://learn.microsoft.com/dotnet/aspire/deployment/azure/local-provisioning (proposed url for this article)

### Article abstract

When you use a method like `AddAzureOpenAI` we automatically add support for the Azure Provisioner. But the Azure Provisioner requires some subscription information to be in user secrets. Here is an example:

```json
{
  "Azyre": {
    "SubscriptionId": "<sub id>",
    "AllowResourceGroupCreation": true,
    "ResourceGroup": "<rg name you want to use>",
    "Location": "East US 2",
    "Tenant": "<your tenant>.onmicrosoft.com"
  }
}
```

---
[Associated WorkItem - 238737](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238737)

**Comment by IEvangelist** [comment]
You mean `Azure`, not `Azyre`, right? 😄

**Comment by timheuer** [comment]
Article should:
- show how to add those values (part of default configuration but we'd recommend as user-secrets on the apphost)
- show the dashboard experience that hints at the problem if you don't have these
- show the Visual Studio tooling that helps you set these and create new RGs if needed, etc.
- probably needs to talk about auth required (meaning you need to actually be logged in to azure to be able to perform action)
