### ISSUE TITLE
[New article]: New resource+component: Qdrant

### ISSUE THREAD

**Issue by timheuer** [dotnet/docs-aspire#590]
### Proposed topic or title

.NET Aspire Qdrant component

### Location in table of contents.

Database

### Reason for the article

New component for the Qdrant vector database

### Article abstract

In this article, you learn how to use the .NET Aspire Qdrant database component. The Aspire.Qdrant.Client library:

- Registers a Qdrant.Client in the DI container for connecting to the Qdrant database.
- Automatically configures logging

**Comment by IEvangelist** [comment]
Is this for `preview-6`, not seeing it in `preview-5`?

**Comment by timheuer** [comment]
It's a few changes away from backport to p5: https://github.com/dotnet/aspire/pull/3416

**Comment by eerhardt** [comment]
This won't make preview5. But once https://github.com/dotnet/aspire/pull/3416 is merged, it will be in preview6. There's no label for p6 yet.
