### ISSUE TITLE
Add instructions for using C# Dev Kit with Aspire

### ISSUE THREAD

**Issue by timheuer** [dotnet/docs-aspire#595]
### Describe the issue or suggestion

On https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio we have instructions for VS/CLI but should have another tab for VS Code which gives the steps to use the C# Dev Kit for the launching/debugging of the Aspire environment. As of this issue post that support is in pre-release channel for the extension, so this isn't urgent but should be scheduled.	

---
[Associated WorkItem - 255429](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255429)

**Comment by IEvangelist** [comment]
There was also recent discussion about adding details in the setup and tooling article for including VS Code instructions. Let's make that happen as part of this.
