### ISSUE TITLE
Split up dashboard page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs-aspire#597]
The dashboard page is very long - https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard

I think it should be split up into its own section with multiple pages inside the Fundamentals section. Pages:
* .NET Aspire dashboard
  * Dashboard overview
  * Using dashboard UI (this page will still be quite long, plus it will get longer in P6 with browser login instructions)
  * Standalone dashboard (right now it [just links to a sample](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard#standalone-mode), should have more detail)
  * Configuration (content can come from https://github.com/dotnet/aspire/tree/main/src/Aspire.Dashboard#net-aspire-dashboard)
  * Security considerations

**Comment by IEvangelist** [comment]
I like it. How would you differentiate between the overview and the using articles? Overview is a simple introduction with links to other content, and the using is essentially the existing content we have now - less an overview?

**Comment by JamesNK** [comment]
Overview would have the most important information:

* What is the dashboard
* How to get it/use it
* Links to other articles

I'd like to aim for preview 6. That preview will have some significant auth changes and has links in UI and console messages to docs.

**Comment by mitchdenny** [comment]
I think you'd probably want an auth section which shows how to set it up and host it securely. Particularly in the OIDC scenario.
