### ISSUE TITLE
Benefits?

### ISSUE THREAD

**Issue by m-brooks** [dotnet/docs-aspire#62]
### Type of issue

Missing information

### Description

As an introductory overview this page/article fails the first rule of selling, by describing features but not benefits. As a techie, I generally prefer documentation to present the features and allow me to make my own mind up as to the benefits rather than being condescended to by marketing bods, but in this case I'll confess that a bit of condescension could be helpful. 
Why would I wish to use this particular approach to orchestration and configuration as opposed to making my own choices from the full selection available on the Microsoft platform?
And what's that adjective "opinionated" referring to?

### Page URL

https://learn.microsoft.com/en-gb/dotnet/aspire/get-started/aspire-overview

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/get-started/aspire-overview.md

### Document Version Independent Id

1b7d0d68-ea99-ae77-0b30-0bafb0195096

### Article author

IEvangelist

**Comment by IEvangelist** [comment]
Hi @m-brooks,

Thank you for posting this issue and asking these questions.

All documentation on the Microsoft Learn Platform is intended to cover the features of products and services, this is not a marketing site. Our content is specifically designed to convey concepts, how-to, tutorials, and even API references, and we strive to avoid "selling" you on anything. I'm happy to add sections discussing the "Why .NET Aspire" and outline the potential perceived benefits.

As for the term "opinionated", it's used to describe the defaults, that are derived of real-world services and the benefits they've discovered from applying said defaults. Does that make sense?

**Comment by davidfowl** [comment]
For reference this is the marketing site https://dotnet.microsoft.com/en-us/apps/cloud 😄
