### ISSUE TITLE
Write guidance for using Entity Framework migrations with Aspire solutions

### ISSUE THREAD

**Issue by gameraliaz** [dotnet/docs-aspire#64]
### Type of issue

Missing information

### Description

my AppHost program.cs:

```
var builder = DistributedApplication.CreateBuilder(args);

var sql = builder.AddSqlServerContainer("sql",password:"P4s$wordBuT$tr0ng",port:14420).AddDatabase("sqldata");

builder.AddProject<Projects.adminendpoint>("admin").WithReference(sql);

builder.Build().Run();
```

Then i want to run it but first make database from my dbcontext that used in admin endpoint.
admin endpoint program.cs is:
```
builder.AddSqlServerDbContext<DataBaseContext>("sqldata");
builder.Services.AddScoped<IDataBaseContext, DataBaseContext>();
```
and my dbcontext is :
```
public class DataBaseContext : DbContext, IDataBaseContext
{
    public DataBaseContext(DbContextOptions dbContextOptions):base(dbContextOptions) { }
    public DbSet<User> Users { get; set; }
    public DbSet<Role> Roles { get; set; }
    public DbSet<UserInRole> UserInRoles { get; set; }
}
```

So how should i use Add-Migration and Update-Database?

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-entity-framework-component?tabs=dotnet-cli

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/database/sql-server-entity-framework-component.md

### Document Version Independent Id

2cd52f56-0ee5-8f04-c2b5-fe52c7f8109f

### Article author

IEvangelist

---
[Associated WorkItem - 186558](https://dev.azure.com/msft-skilling/Content/_workitems/edit/186558)

**Comment by davidfowl** [comment]
Excellent question! This is one of the big problems we hit while developing eshop as well. Adding migrations requires putting a connection string in the appSettings.json or EF will blow up. 

For update database, we for the first preview, we settled on a separate application that runs as part of the app:

https://github.com/dotnet/aspire/tree/main/samples/eShopLite/CatalogDb

See https://github.com/dotnet/aspire/issues/398 for more info.

**Comment by peteraritchie** [comment]
> Excellent question! This is one of the big problems we hit while developing eshop as well. Adding migrations requires putting a connection string in the appSettings.json or EF will blow up.

So, the connection string in code will only be known to the other project at run-time.  Even if the connection string was in the appsettings for AppHost, the other project would only know about the value at run-time, not at design-time (i.e. when using `dotnet ef`).  Bummer.

**Comment by davidfowl** [comment]
Yes this is a problem.

**Comment by IEvangelist** [comment]
@davidfowl - I assume we need to call this out in docs? If so, what exactly should we say?

**Comment by peteraritchie** [comment]
@IEvangelist I kind of feel like [NET Aspire SqlServer Entity Framework Core component](https://learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-entity-framework-component?tabs=dotnet-cli) depends on that guidance.

**Comment by JHTaxa** [comment]
FWIW, this is still poorly documented. It just says run the migration, it doesn't say any of the above, and of course the migration system doesn't spin a postgress database nor is there any tooling to do so so you have to have a second instance of postgress around for migrations at all times.

Ideally we could use a DesignTimeFactory in the AppHost to generate the new migration after it spun up the database engine and applied the migrations that were already there.

Or we would be able to keep the containers running always and not have them shutdown and then we could reference them by hand I guess.

**Comment by CamSoper** [comment]
@JHTaxa The [article](https://learn.microsoft.com/dotnet/aspire/database/ef-core-migrations) that was written depended heavily on the [sample](https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseMigrations) written by James-Newton King. It spins up a migration service at runtime to run the migrations using the same context as the app and then shut down.

Your method looks fine to my eyes, but I'd feel better if David Fowler or James NK had a chance to chime in. Can you please open another issue in this repo specifically regarding your solution?

**Comment by onionhammer** [comment]
Does this sample tackle how to apply updates via console.. for example to rollback a migration?

**Comment by JHTaxa** [comment]
> @JHTaxa The [article](https://learn.microsoft.com/dotnet/aspire/database/ef-core-migrations) that was written depended heavily on the [sample](https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseMigrations) written by James-Newton King. It spins up a migration service at runtime to run the migrations using the same context as the app and then shut down.
> 
> Your method looks fine to my eyes, but I'd feel better if David Fowler or James NK had a chance to chime in. Can you please open another issue in this repo specifically regarding your solution?

I'd argue that my solution should be part of the article and sample. As it is right now the article is incomplete and can't work without major hacks (i.e. a second database docker instance running).  My version solves the problem and should be added to both the sample and the article.

If that needs to be a new issue, then ok, but really the article and sample are insufficent to actually make ef core migrations work.

PS: This is going to be the exact same issues with OpenAPI documentation in .net 9 because it has to execute the endpoints to be able to generate the documentation, it doesn't work with reflection.

**Comment by CamSoper** [comment]
I seriously don't mean to be flippant, and I'm trying hard to understand, but are we talking about the same article?

I just followed the steps in the article to the letter except I replaced the SQL Server provider with the Npgsql provider, and it [seems to run the migrations on startup just fine](https://github.com/MicrosoftDocs/aspire-docs-samples/tree/solution-postgres). 

To be completely transparent, I'm kinda a latecomer to the Aspire docs party, so I'm playing catch-up a bit. I'm not sure what you mean about requiring a second docker container in this context. 

Please forgive my thrashing as I try to understand the problem. I would still like this to be opened under a new issue so we can get the right eyes on it (but also so I can track my work internally).

**Comment by JHTaxa** [comment]
You missed the part that doesn't work just fine: Creating the migrations in the first place.

It requires that you either have a fake docker container that you have a known connection string, or you run your host, get the connection string, then prey that Vs.net didn't lock your data project and it will build and run again with that new connection string you put in just for the purpose of creating the migration.

My solution solves all of that and allows migration creation to just work.

If you add @davidfowl 's WaitForCompletion() function, you can block until the migrations are complete so that your services don't throw errors on startup in the host like the suggested example does right now.

Honestly, the EF team or someone needs to take what I just did, make it generic, add in the sample service as a job that can be script built as a pre-deploy job and have it all just work out of the box.

**Comment by onionhammer** [comment]
You don't need a database connection to create migrations

**Comment by JHTaxa** [comment]
The first migration definitely did, a faux connection string didn't work and failed.  After that I don't know because I fixed it with a proper IDesignTimeDbContextFactory that uses the AppHost which solves the problem correctly.

**Comment by JHTaxa** [comment]
It has to construct the project wit DI and the actual data context to do so. If you have the most simplistic scenario, that probably works. But if you're doing any advanced stuff that won't work.

**Comment by AndriySvyryd** [comment]
It's true that in some cases the ef tools will fail to run when a hostbuilder is used, so it makes sense to mention that a
[IDesignTimeDbContextFactory<>](https://learn.microsoft.com/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-a-design-time-factory) implementation can be added to short-circuit this logic (note that this only works reliably starting with EF Core 9.0.0)

Also, the connection string isn't required by the tool, so the implementation can be even simpler:

```C#
public sealed class DataContextDesignTimeFactory : IDesignTimeDbContextFactory<DataContext>
{
    public DataContext CreateDbContext(string[] args)
        => new DataContext(new DbContextOptionsBuilder<DataContext>().UseNpgsql().Options);
}
```
