### ISSUE TITLE
Create a persistent password shouldn't point to sample method

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs-aspire#672]
https://github.com/dotnet/docs-aspire/blob/main/docs/fundamentals/persist-data-volumes.md#create-a-persistent-password

Creating a persistent password should show how to set the parameter value and not show [these helper extension methods](https://github.com/dotnet/aspire-samples/blob/fb4adeb0800c941c97dc062335ea71eba55eec6c/samples/Shared/ParameterExtensions.cs).

Instead, we should show how to set parameter values named appropriately:

We should document all of the resources that generate passwords, and we should talk about the parameter names for those generated passwords. We should also show how you can set the passwords without changing any code.

- Postgres
- SqlServer
- MySql
- RabbitMq

For example:

```C#
var builder = DistributedApplication.CreateBuilder(args);

var db = builder.AddSqlServer("sql").AddDatabase("db");

builder.AddProject<Projects.WebApplication10>("api")
       .WithExternalHttpEndpoints()
       .WithReference(db);

builder.Build().Run();
```

You can set a persistent password for sqlserver by setting the parameter value in user secrets in the AppHost project:

```
dotnet user-secrets add Parameters:sql-password {somepassword}
```

This will override the auto generated password used by the sql server resources above. The pattern for auto generated password parameters is `Parameters:{resourcename}-password`.

cc @eerhardt

**Comment by eerhardt** [comment]
I believe @DamianEdwards's intention with this code was that when you don't `dotnet user-secrets add ...` and just run the app you get an error. People were confused and thought that the app was broken. So the thinking was to "just make it work".

**Comment by theo-albers** [comment]
> We should document all of the resources that generate passwords, and we should talk about the parameter names for those generated passwords.

Would it be possible to dump the used environment variables to the console via a config switch? That way you wouldn't have to document it, disconnected from the code.

**Comment by davidfowl** [comment]
I think that's an unrelated feature request.

**Comment by tmds** [comment]
I found this issue while looking for any issues about the _Create a persistent password_ section.

Currently this section shows some code and it's not clear how Aspire would be using the `samplepassword` value.

**Comment by rmarinho** [comment]
Yeah I hitted this myself doing the eShop workshop to get familiar with aspire. I did tried to add as Parameter but then it said it didn't found it on my settings.

**Comment by rudivs** [comment]
Just to mention, the correct command to set the persistent password is:

```
dotnet user-secrets set Parameters:sql-password {somepassword}
```

If you don't have user secrets configured yet, you first need to run:

```
dotnet user-secrets init
```

**Comment by davidfowl** [comment]
Good call out. The apphost should have a user secrets id set from preview 5 onwards (so it should be init-ed already).
