### ISSUE TITLE
[New article]: Integration/functional testing with .NET Aspire

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/docs-aspire#685]
### Proposed topic or title

Integration/functional testing with .NET Aspire

> NOTE: Proposed URL is: https://learn.microsoft.com/dotnet/aspire/testing
>       this would be a top level landing page for testing in Aspire and
>       will be linked to from aka.ms/dotnet/aspire/testing so we can
>       easily reference the conceptual testing docs from XML doc comments.

### Reason for the article

We don't currently have an article that covers using `DistributedApplicationTestingBuilder` in a unit testing framework such as Xunit.

```csharp
[Fact]
public async Task GetWebResourceRootReturnsOkStatusCode()
{
  // Arrange
  var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.MyAspireApp_AppHost>();
  await using var app = await appHost.BuildAsync();
  await app.StartAsync();

  // Act
  var httpClient = app.CreateHttpClient("webfrontend");
  var response = await httpClient.GetAsync("/");

  // Assert
  Assert.Equal(HttpStatusCode.OK, response.StatusCode);
}
```

Its important to provide this information because if people just try to replicate what they have in their top-level API they'll eventually run into inotify exhaustion issues on Linux build machines (among other resource issues).__

### Article abstract

In addition to unit testing which is common in any .NET project, we recommend the use of the `DistributedApplicationTestingBuilder` type to enable the creation of functional and integration tests. The `DistributedApplicationTestingBuilder` supports testing by making it easy to resolve endpoint references to services running within the AppHost in the context of an integration test as well as help avoid resource leakage when creating multiple AppHosts over multiple tests in a single test run.

**Comment by DamianEdwards** [comment]
Should we do this for preview.6 now?
