### ISSUE TITLE
Add architecture diagram to the standalone dashboard page

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs-aspire#686]
Here's my beautiful attempt. Each app uses the otlp protocol to send telemetry to the otlp endpoint. The dashboard talks to a resource server over grpc to get information about running resources.

![image](https://github.com/dotnet/docs-aspire/assets/95136/e1832b8a-1931-4031-9b55-75a0938cb29b)

---
[Associated WorkItem - 246160](https://dev.azure.com/msft-skilling/Content/_workitems/edit/246160)

**Comment by IEvangelist** [comment]
![architecture-diagram](https://github.com/dotnet/docs-aspire/assets/7679720/586e6e3f-804a-444b-abaf-92137678d9da)

Something like this?

**Comment by IEvangelist** [comment]
Are we calling these "apps" or are they really "resources"?
