### ISSUE TITLE
[WebToolsE2E][Aspire][Document]Some more updates are needed to "Build your first .NET Aspire app" instructions using VS with aspire

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/docs-aspire#720]
### Describe the issue or suggestion

Issue description
In "Build your first .NET Aspire app" doc, we need to make some updates to the instructions for Preview 7.

- [ ] In Prerequisites, VS version should be 17.10 or higher

- [ ] **Issue 1:** 
[For Create the .NET Aspire template](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio#create-the-net-aspire-template) section, document show "Ensure that Use Redis for caching(requires Docker) is checked and select Create"
![image](https://github.com/dotnet/docs-aspire/assets/41678874/866cf873-141a-4d99-bc09-0dfaa5359234)
actual: It shows "requires a supported container runtime", so need update the screenshot.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/37731862-037e-4554-8f5f-935caac55481)

- [ ] **Issue 2:** 
For [Test the app locally ](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio#test-the-app-locally)section, document shows "redis:7.2.4" and "localhost:57500" for cache, show "http://..." for apiservice, show "http://localhost:5044" for webfrontend
![image](https://github.com/dotnet/docs-aspire/assets/41678874/a5002e61-cdf9-4415-af91-d0e44c2945d4)

**actual**: show "docker.io/library/redis:7.0.4" and "tcp://localhost:57759" for cache, show "https://....; http://..." for apiservice,
show "https://...,http://..."  for webfrontend.  so need update the screenshot.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/bd52e677-24cb-4ae7-85e3-2a2136a332c2)

          
For [Explorer the .NET Aspire dashboard](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio#explore-the-net-aspire-dashboard) section,  the screenshot also need update as same as above issue.

- [ ] **Issue 3:** 
For[ .NET Aspire app host project](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio#net-aspire-app-host-project) section,  document show screenshot:
![image](https://github.com/dotnet/docs-aspire/assets/41678874/23db186f-5b53-4af2-aeec-f51dc07e767c)

Actual: Have this line "<UserSecretsId>75068497-9774-40c7-915d-eedd99473268</UserSecretsId>", so document need update the screenshot.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/dce5c87a-fd2c-42d5-8960-2661aef8355a)

- [ ] **Issue 4:**  
For [.NET Aspire app host project](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio#net-aspire-app-host-project) section,  document show below screenshot:
![image](https://github.com/dotnet/docs-aspire/assets/41678874/77e2bc55-7f9a-4ffb-adf9-bc4db5bb6f47)

Actual: Have this line " .WithExternalHttpEndpoints()" in line 8, so need update the screenshot.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/a7415f5f-941c-4d14-b52e-dd145a4ab8ef)

- [ ] **Issue 5:** Document show screenshot:

![image](https://github.com/dotnet/docs-aspire/assets/41678874/451d40c4-1805-4cd7-9a16-efe26b22da60)
![image](https://github.com/dotnet/docs-aspire/assets/41678874/d6f4fc8f-a843-4697-aa04-0cd7d7fc5811)

Actual: show as below, so need update the screenshots.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/53374154-a4c9-4b11-be4e-389d61fe102e)
![image](https://github.com/dotnet/docs-aspire/assets/41678874/67ac3a75-5e7f-41e1-9e2e-cdcd6117d3b6)

---
[Associated WorkItem - 253420](https://dev.azure.com/msft-skilling/Content/_workitems/edit/253420)

**Comment by balachir** [comment]
@bradygaster this is the issue I was showing you during the meeting today. I'll try to send a PR on Monday for preview-7 if the doc team doesn't get to it by then.

**Comment by bradygaster** [comment]
thanks @balachir !!!

**Comment by v-yuwzh** [comment]
Verify this document has been updated, thanks a lot.
