### ISSUE TITLE
[WebToolsE2E][Aspire][Document]Some more updates are needed to "Deploy a .NET Aspire app to Azure Container Apps" instructions using VS with aspire

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/docs-aspire#722]
### Describe the issue or suggestion

Issue description
In "Deploy a .NET Aspire app to Azure Container Apps" doc, we need to make some updates to the instructions for Preview 6.

**Issue 1:**
For [Create the .NET Aspire template ](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=visual-studio%2Cinstall-az-windows%2Cpowershell&pivots=azure-azd#create-the-net-aspire-template)section, document show requires Docker
![image](https://github.com/dotnet/docs-aspire/assets/41678874/d3127883-ca81-41eb-a5bf-f04c7c02b61a)

Actual: show "requires a supported container runtime", so the document need update.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/b8d2f372-367c-4661-9e34-fccaebee1daf)

**Comment by alexwolfmsft** [comment]
This issue has been fixed in a recent PR.

**Comment by v-yuwzh** [comment]
verify this issue has been fixed.
