### ISSUE TITLE
Add details about using the MongoDB component with MongoDB Atlas on Azure

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/docs-aspire#744]
Details TBD

**Comment by LuceCarter** [comment]
@DamianEdwards Please include me in this/assign to me.

I'm the C# Developer Advocate at MongoDB! 😄

**Comment by IEvangelist** [comment]
Hi @LuceCarter - I'll assign it to you, feel free to update this article:

- [🔗 .NET Aspire MongoDB database component](https://learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-component)
- [📝 Markdown file](https://github.com/dotnet/docs-aspire/blob/main/docs/database/mongodb-component.md)

**Comment by sundog358** [comment]
Is there any updates or guidance for this ?

**Comment by sundog358** [comment]
Is there any docs for mongo db atlas on ?

**Comment by IEvangelist** [comment]
> Is there any docs for mongo db atlas on ?

We have a component doc on MongoDB here:

- https://learn.microsoft.com/en-us/dotnet/aspire/database/mongodb-component

And we have a section in the existing manifest content here:

- https://learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format#mongodb-resource-types

But we do not have any content for MongoDB Atlas.

**Comment by LuceCarter** [comment]
@IEvangelist Can this be closed now the component page has been updated?
