### ISSUE TITLE
[WebToolsE2E][Aspire][Document]Some more updates are needed to "Deploy a .NET Aspire app using the Azure Developer CLI and GitHub Actions" instructions using VS with aspire

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/docs-aspire#747]
### Describe the issue or suggestion

Issue description
In "Deploy a .NET Aspire app using the Azure Developer CLI and GitHub Actions" doc, we need to make some updates to the instructions for Preview 6.

**Issue 1**

For [Create the .NET Aspire template](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio&pivots=github-actions#create-the-net-aspire-template) section, document show "require Docker"
![image](https://github.com/dotnet/docs-aspire/assets/41678874/c7f5f705-b3ce-439a-9ed7-50042e3d39a4)

Actual: Show "requires a supported container runtime", so need update document.

![image](https://github.com/dotnet/docs-aspire/assets/41678874/17a2b28a-b6a8-4d39-b755-15917ec4ee51)

**Issue 2**

For [Initialize the template](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio&pivots=github-actions#initialize-the-template) section, document show after do the step# 4 will pop up code as below and let select webfrontend
![image](https://github.com/dotnet/docs-aspire/assets/41678874/21211bcc-18c3-4839-a060-3ca388890044)

Actual: after do the step#4, don't let you select webfrontend, skip the step#5. so need update the document.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/e975c0df-1567-4152-8f18-43280fb42790)

**Issue 3**

For [Create the GitHub repository and pipeline](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio&pivots=github-actions#create-the-github-repository-and-pipeline) section, document show after do the step#4, you will do step#5 "Select Create a new private GitHub repository to configure the git remote"
![image](https://github.com/dotnet/docs-aspire/assets/41678874/1b48d6a5-84ac-4c8c-9e55-b3ae03834ce9)

Actual: after do the step#4, let select "HTTPS" or "SSH"...., don't let select "Create a new private GitHub repository", and after do the many steps, then let you select "Create a new private GitHub repository". so before step#5 need add some steps, the document need update.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/32221771-2bf5-4781-a72e-006be2b18344)

**Comment by v-yuwzh** [comment]
@IEvangelist, about Issue#2, for section [Initialize the template](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio&pivots=github-actions#initialize-the-template), document show step#1~step#7,

actual: the step is step#1, step#2, step#4, step5, step#3,  step#7, step#6 is redundant, could you help  check and update the document?
![image](https://github.com/dotnet/docs-aspire/assets/41678874/0b3f1992-7ae4-46e8-99a2-a7bd78bcf097)

**Comment by Rita003** [comment]
@IEvangelist About Issue#2, for section [Initialize the template](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=dotnet-cli&pivots=azure-azd#initialize-the-template), the steps order need to update 
Actual: The step order need update to step#1, step#2, step#4, step5, step#3, step#7, it doesn't need to select webfrontend of the step#6, skip the step#6. so need update the document [Deploy .NET Aspire apps to Azure Container Apps - .NET Aspire | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=dotnet-cli&pivots=azure-azd), could you please help to check and update the document?
