### ISSUE TITLE
EF SQL doc outdated in preview 6

### ISSUE THREAD

**Issue by CamSoper** [dotnet/docs-aspire#753]
`builder.AddSqlServer()` doesn't work until reference to `Aspire.Hosting.SqlServer` package is added. Is this a known change in preview 6, @IEvangelist?

Also there's no longer any `hostPort` parameter for the `.WithEndpoint` extension.

**Comment by IEvangelist** [comment]
Hi @CamSoper - yeah, those hosting packages were all updated in preview 5, detailed here:

- https://learn.microsoft.com/fr-fr/dotnet/aspire/whats-new/preview-5?tabs=dotnet-cli#packaging-changes

And preview 6 was a much smaller window (faster iteration), which happened just earlier this week. The `hostPort` parameter was renamed to just `port`.

- https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-6
