### ISSUE TITLE
Non AZD Azure deployment article is out of date

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs-aspire#757]
https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=visual-studio%2Cinstall-az-windows%2Cpowershell&pivots=azure-bicep

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=visual-studio%2Cinstall-az-windows%2Cpowershell&pivots=azure-cli

- It uses the template with http+https scheme now which means service discovery information needs to be set

cc @bradygaster @DamianEdwards

**Comment by bradygaster** [comment]
cc @alexwolfmsft who is working on the deployment doc updates now. We toyed with - and like - the idea of completely removing the `az cli` section. Any objections, @davidfowl and @DamianEdwards?

**Comment by alexwolfmsft** [comment]
> cc @alexwolfmsft who is working on the deployment doc updates now. We toyed with - and like - the idea of completely removing the `az cli` section. Any objections, @davidfowl and @DamianEdwards?

We also proposed either removing the Bicep section or reducing it down to an overview and linking out to a sample repo that includes the finalized bicep scripts to avoid copy/pasting large blocks of text.

**Comment by davidfowl** [comment]
I think we should remove them as well. Hand rolling what azd does is kinda painful 😄. @DamianEdwards ?

**Comment by DamianEdwards** [comment]
The only reason for keeping it I think would be that it helps to explain all that is being automated by azd. This could be useful for folks who aren't ready/willing to adopt azd for deployment but are using bicep and/or az as this make it pretty clear what's involved.

**Comment by davidfowl** [comment]
Then someone needs to validate these manual steps every release.

**Comment by IEvangelist** [comment]
> Then someone needs to validate these manual steps every release.

Not it! 🥸

**Comment by DamianEdwards** [comment]
The article doesn't seem to actually contain details for deploying with `az` or bicep anymore, despite what the introduction paragraph says. Am I missing something?

**Comment by IEvangelist** [comment]
> The article doesn't seem to actually contain details for deploying with `az` or bicep anymore, despite what the introduction paragraph says. Am I missing something?

Yeah, there's been a lot of recent changes around deployment. Lots of moving parts, looks like this article is now only focusing on `azd` but the intro wasn't updated.

**Comment by IEvangelist** [comment]
This was closed in 8d87fe7.

**Comment by davidfowl** [comment]
@vhvb1989 can we document the way parameters work in this article ?
