### ISSUE TITLE
Out-of-date documentation

### ISSUE THREAD

**Issue by shaun-rostami** [dotnet/docs-aspire#763]
Hi.
I just tried using version 8.0.0-preview.6.24214.1 of the `Aspire.StackExchange.Redis` package in my component-consuming project which seems to provide the `builder.AddRedisClient` extension method instead of `builder. AddRedis` and it's a breaking change but the documentation hasn't been updated. Also in the app host project, even though I have referenced the same package, I can't use the following line in the documentation page:
`var redis = builder.AddRedis("redis");`
as `AddRedis` or `AddRedisClient` cannot be found. Any idea?

**Comment by davidfowl** [comment]
[AddRedisClient](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.aspireredisextensions.addredisclient?view=dotnet-aspire-8.0#microsoft-extensions-hosting-aspireredisextensions-addredisclient(microsoft-extensions-hosting-ihostapplicationbuilder-system-string-system-action((aspire-stackexchange-redis-stackexchangeredissettings))-system-action((stackexchange-redis-configurationoptions)))) should be available

**Comment by shaun-rostami** [comment]
It's not. Would you be able to share a sample .NET 8 application with a similar structure that uses the same nuget package and has AddRedisClient in its App Host startup?

**Comment by davidfowl** [comment]
https://github.com/davidfowl/AspireWithRedis
