### ISSUE TITLE
Disambiguate Hosting and Components in docs

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs-aspire#801]
> Closing as we are locking down for shipping the `8.0.0` GA release and we aren't convinced this is the correct long term decision (given the above feedback/discussion). We will consider ways we can make the documentation more clear on what these libraries are and how to tell the difference between the `Aspire.Hosting.*` libraries and the `Aspire.*` libraries.

_Originally posted by @eerhardt in https://github.com/dotnet/aspire/issues/3998#issuecomment-2088546771_
            

---
[Associated WorkItem - 255392](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255392)

**Comment by JamesNK** [comment]
I think this is also useful in the extensibility section.

Imagine you're a .NET library owner and you want to make your stuff work great with Aspire. You need an overview of information about extensibility options, including resources vs components.

Should I create a resource? Should I create a component? What packages should I have? What are they called and tagged? Do I make them in my repo or the Aspire repo? etc

**Comment by bradygaster** [comment]
This is a confusing spot for customers. I think it might be more confusing for Preview1-5 customers than it will be for GA-and-beyond, but I do agree we need a clear doc - or section of a doc - in the difference between the two.

**Comment by IEvangelist** [comment]
Are these accurate statements?

- Resources are always related to hosting concerns (i.e.; expressed in the app host).
- Components are always consumers of some resource and are never expressed in the app host.
