### ISSUE TITLE
[docs - update][azd] Last changes on azd and the side effects

### ISSUE THREAD

**Issue by vhvb1989** [dotnet/docs-aspire#805]
# Aspire <-> Azd / VS Doc updates

Please take a look to the changes below and consider what to bubble up as part of Aspire next releases.

## 1) azure.yaml from AppHost project folder

Folks can run `azd init` from the root of the project or inside the appHost folder. Running `azd init` in app host directory will create azure.yaml in thet app host directory. For existing projects where azure.yaml is already in the root of the project, azd will continue to work.

Consider updating:
- Best-practice: where docs mention running `azd init` in root, change docs to mention run `azd init` in app host directory instead.
  - Recommend azd commands to also be ran in app-host project directory i.e., azd init, azd up(azd provision, azd deploy) etc.

## 2) infra synth output

azd was updated to write all the `azd infra synth` outputs inside the AppHost project, writing yaml manifests and bicep files to a folder named `infra`.
Existing projects using azure.yaml and infra folder on the root will continue to work, but running `azd infra synth` will write outputs to the AppHost (breaking change). Please ask folks to delete the infra folder from the root if they previously use `infra synth`
Consider:
  - Clean up manifest folder from service folders (as it will be ignored)

## 3) container.v0 deployment time moved from infra to after-infra

Folks will no longer see containerApps for managed services created as part of the infrastructure deployment (azd provision). App containers will be created at the same time as the projects and docker images.

## 4) Container Apps Environment type updated to consumption

This is a breaking change for folks expecting to keep working in a previously deployed project. Deployment will fail because the type of the container environment can't be changed after it is created. The workaround in case folks want to keep using an existing project is to use `azd infra synth` and update the type. 
 
## 5) Aspire dashboard updates/how-to for CLI and VS experience.

Aspire dashboard is already supported beyond EUAP locations, but it is still under an azd feature flag, folks must run `azd config set alpha.aspire.dashboard on` for deploying the dashboard and having azd to display the url at the end.
When the flag is enabled, folks can also run `azd monitor` to automatically launch the dashboard.

## 6) Cleanup resources update for VS experience i.e., with/without force delete etc.

Delete environment within Visual Studio. Ability to choose whether Azure resources should be removed as well.

References:
https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment
https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth
https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions
https://learn.microsoft.com/en-us/dotnet/aspire/database/sql-server-component-deployment

FYI @rajeshkamal5050 @ellismg

**Comment by alexwolfmsft** [comment]
Hey @vhvb1989 , I'm working on updating relevant docs with these changes, but some of them I have been unable to verify, notes with the corresponding number below:

1) I'm still seeing azd artifacts written to the root of the project if you run the command from the root. If i'm understanding correctly, aren't these supposed to be created in the AppHost folder now?
2) Infra synth also still writes to the root when run in the root.
3) Verified successfully.
4) Verified successfully.
5) I didn't see any change in behavior when enabling the alpha feature.
6) I still get the option to use whether to remove the Azure resources on the latest VS preview.


I'm using azd 1.9 with .NET Aspire Preview 6  - is there a different version I should use?

**Comment by vhvb1989** [comment]
For 1 and 2, adding @ellismg 

For 5, there's no change on behavior, but, when aspire dashboard is enabled, you should see the aspire dashboard url at the end of deploy.

For 6, adding @weikanglim

**Comment by weikanglim** [comment]
@alexwolfmsft For 1 and 2, `azd init` will still write artifacts in the directory being ran in. But we would recommend by default `azd init` to be ran in app host directory. @ellismg correct me if I'm wrong.

For 6, the delete environment action is available under the "More actions" dropdown, like so:
![image](https://github.com/dotnet/docs-aspire/assets/2322434/004d502a-82fd-4db3-aed9-eb19f30b35b5)

Preview 6 should have these changes.

**Comment by alexwolfmsft** [comment]
> For 1 and 2, adding @ellismg
> 
> For 5, there's no change on behavior, but, when aspire dashboard is enabled, you should see the aspire dashboard url at the end of deploy.
> 
> For 6, adding @weikanglim

Right, the only URLs I saw output were the web and api URLs.

**Comment by ellismg** [comment]
One thing to note, @alexwolfmsft - For folks that wanted to continue to have `azure.yaml` in a different folder than their app host, but have `infra synth` write the shared infrastructure into the app host directory, we just merged https://github.com/Azure/azure-dev/pull/3876 which will be in 1.9.1 and allow you to set the path to where the shared infrastructure bicep files are written.
