### ISSUE TITLE
Standalone dashboard help topic should show or reference the setting to disable dashboard authentication

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/docs-aspire#820]
### Describe the issue or suggestion

If you are using the dashboard as a standalone viewer for telemetry, then the fact that its authenticated by default is going to be a pain and friction to usage. We have the option to disable the authentication, which is referenced in the configuration page, but is not referenced in the standalone page.

With the need to be secure by default, I would suggest that we don't change the command-line shown at the top of the file, but do add a comment to set `DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS = true` to the end of the [Login to the Dashboard](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone#login-to-the-dashboard) section so that once they have tried it, they will realize if they want to disable authentication or not, and not have to go hunting around to figure out how to do it.

---
[Associated WorkItem - 255391](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255391)

**Comment by bradygaster** [comment]
I didn't even know that was a feature.
