### ISSUE TITLE
Rename component "Azure AI Search Documents" to "Azure Search Documents"

### ISSUE THREAD

**Issue by sebastienros** [dotnet/docs-aspire#826]
Per the document and package name: https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Azure.Search.Documents

File to fix: https://github.com/dotnet/docs-aspire/blob/main/docs/azureai/azureai-search-document-component.md

**Comment by IEvangelist** [comment]
Yes and no... See https://github.com/dotnet/docs-aspire/pull/863#issuecomment-2100785462

**Comment by sebastienros** [comment]
Then instead I will fix the component's README. Thanks
