### ISSUE TITLE
Consider changing link to Aspire Workload to point to instructions on how to install it.

### ISSUE THREAD

**Issue by joperezr** [dotnet/docs-aspire#834]
### Describe the issue or suggestion

As of today, in setup-tooling instructions we have a bullet point that just lists `.NET Aspire Workload` as a requierment, but if you click on that link it just takes you to general dotnet workload install command docs. Should it instead point you to the actual docs on how to install Aspire specifically? As-in, tperhaps to the CLI instructions on how to do so in the same page?

This is the line in question:

https://github.com/dotnet/docs-aspire/blob/0964e853ea1aa552f07565e46af20527a7141b16/docs/fundamentals/setup-tooling.md?plain=1#L23

---
[Associated WorkItem - 255387](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255387)

**Comment by bradygaster** [comment]
@IEvangelist could probably make an include, if one doesn't already exist. I presume we *want* the experience to be documented consistently, right?
