### ISSUE TITLE
Consider adding troubleshooting info on setup instructions

### ISSUE THREAD

**Issue by joperezr** [dotnet/docs-aspire#837]
### Describe the issue or suggestion

Our Setup instructions from the command line don't currently have any troubleshooting information, and we do know that things can go wrong especially when folks try to install the workload via the CLI and have some NuGet.config that is changing the default feeds. The instructions we have currently would fail in that case, and we don't have any info currently to help them diagnose and fix the issue. If @IEvangelist or @bradygaster confirm that it is fine to add troubleshooting info in that setup page, I'd gladly contribute to it.

---
[Associated WorkItem - 255187](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255187)

**Comment by danmoseley** [comment]
I'd say go ahead and write the info, we clearly need it and they can then tell us the right place for it.
