### ISSUE TITLE
Update Docs to Reference AppHost NuGet Packages

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/docs-aspire#844]
### Describe the issue or suggestion

With P5 there are app host packages that need to be installed. We should update all docs on how to do this.

---
[Associated WorkItem - 255390](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255390)

**Comment by bradygaster** [comment]
During the meeting we basically concluded that any component doc should include:

1. The name of the nuget package
2. The name of the hosting nuget package
3. Where to install both (as in, in which project - we shouldn't presume folks know to put hosting packages into the hosting project and vice-versa, we should be explicit about this)

**Comment by jamesmontemagno** [comment]
And the normal flow for folks will be to install something into their apphost first and then integrate it into their client project so we should be consistent if possible
