### ISSUE TITLE
Add a troubleshooting section for getting started with Aspire (or generally)

### ISSUE THREAD

**Issue by danmoseley** [dotnet/docs-aspire#845]
### Describe the issue or suggestion

We should have a troubleshooting page for common errors during Aspire development.

Eg., when launching the sample for the first time, I agreed to install the localhost cert, but didn't realize I had to close all my browser tabs. Edge refused to connect to the untrusted localhost. At that point I'm going to go to StackOverflow. (Maybe similar if somehow I hit no on the dialog and now want to recover.) This isn't Aspire specific but Aspire defaults to HTTPS plus some folks reading the docs will be new to ASP.NET.

I expect this section over time will include many Aspire-specific notes.

---
[Associated WorkItem - 253148](https://dev.azure.com/msft-skilling/Content/_workitems/edit/253148)

**Comment by danmoseley** [comment]
[for that specific issue if anyone comes here, I ended up doing `dotnet dev-certs https --clean` and
`dotnet dev-certs https --trust` which will help in other situations although in my particular case probably jsut needed to close all browser tabs]

**Comment by danmoseley** [comment]
Perhaps it fits here somehow
https://github.com/dotnet/docs-aspire/blob/4665176c038ba13ca2ab8f9f035ce114625e49ea/docs/toc.yml#L187

but it needs to be findeable easily from the getting started walkthroughs.

**Comment by IEvangelist** [comment]
I recommend that we include common troubleshooting guidance, per topic, as done with the [Allow unsecure transport in .NET Aspire](https://learn.microsoft.com/en-us/dotnet/aspire/troubleshooting/allow-unsecure-transport?tabs=unix). We should really encapsulate each topic into its own article, to help with SEO, and ensure consumers are successful. With that said, we should also add general links to additional sources of troubleshooting - like proposed in #856.
