### ISSUE TITLE
Example config for "HealthChecks": false should be "DisableHealthChecks": true 

### ISSUE THREAD

**Issue by oising** [dotnet/docs-aspire#853]
The sample for disabling health checks via config is very likely out of date:

As per: https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/health-checks

**Comment by IEvangelist** [comment]
This would be work for `preview-7` onward... as `preview-6` these bits were named `HealthChecks`, and didn't have the `Disable` prefix, inverting their usage.

**Comment by oising** [comment]
> This would be work for `preview-7` onward... as `preview-6` these bits were named `HealthChecks`, and didn't have the `Disable` prefix, inverting their usage. Go search the .NET Aspire API docs: https://learn.microsoft.com/en-us/dotnet/api/aspire.seq.seqsettings.healthchecks?view=dotnet-aspire-8.0#aspire-seq-seqsettings-healthchecks

ah, okay -- sorry about that. I've got my head buried in `main` so I'm only seeing the latest bits.

**Comment by IEvangelist** [comment]
No worries at all. Thank you
