### ISSUE TITLE
[New article]: Aspire integration with ACA

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/docs-aspire#854]
### Proposed topic or title

Create and deploy Aspire apps with ACA

### Reason for the article

The ACA integration is a critical piece of the story for Cloud Native Aspire applications and completes the developer inner loop from code to cloud scenario. It would be helpful to have an article that describes the use of Azure tooling (both azd cli and azure cli) to deploy Aspire applications and to enable/dsiable the Aspire just in time view of the dashboard in the Azure portal

### Article abstract

The ACA integration is a critical piece of the story for Cloud Native Aspire applications and completes the developer inner loop from code to cloud scenario. It would be helpful to have an article that describes the use of Azure tooling (both azd cli and azure cli) to deploy Aspire applications and to enable/dsiable the Aspire just in time view of the dashboard in the Azure portal

**Comment by kvenkatrajan** [comment]
CC : @bradygaster , @IEvangelist

**Comment by alexwolfmsft** [comment]
Hello, we currently have a few docs that detail deploying .NET Aspire to ACA, along with a couple work items for additional content. When combined with this doc https://review.learn.microsoft.com/en-us/azure/container-apps/aspire-dashboard?branch=pr-en-us-274262&pivots=azurecli it seems like Aspire deployments to ACA and dashboard configurations will be covered pretty well - is there anything specific you're looking for that isn't covered by these?

We could add a contextual link in the Aspire docs to point to the container apps article about the dashboard.

Existing deployment content:

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=visual-studio%2Cinstall-az-windows%2Cpowershell&pivots=azure-azd

**Comment by alexwolfmsft** [comment]
Closing this for now as it appears that existing docs cover these scenarios.
