### ISSUE TITLE
Dapr feedback

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs-aspire#947]
Feedback for https://learn.microsoft.com/en-us/dotnet/aspire/frameworks/dapr?tabs=dotnet-cli

1. builder.AddDapr(); is not required. It is added automagically when you use `WithDaprSideCar`
2. `WithDaprSidecar` does not need the name specified, it's optional.
3. The mega code sample show not show the most complex configuration, it should show the most basic configuration and then explain that more advanced configuration is possible with AddDapr and WithSideCar.
4. We don't talk about using dapr components with the API. There are 2 strongly typed ones modeled using aspire APIs and then there are all of the yaml based OSS components.

---
[Associated WorkItem - 261424](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261424)

**Comment by IEvangelist** [comment]
@davidfowl 

> 1. `builder.AddDapr();` is not required. It is added automagically when you use `WithDaprSideCar`

The triple slash for the `WithDaprSidecar` needs to state that at the bare minimum. It's completely unreasonable for a consumer to make the assumption that a call to `WithDaprSidecar` also calls `AddDapr`.

> 2. `WithDaprSidecar` does not need the name specified, it's optional.

It's not optional, it's a non-nullable `appId` parameter. Not according to the [source code, see here](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/IDistributedApplicationComponentBuilderExtensions.cs#L21):

```cs
    public static IResourceBuilder<T> WithDaprSidecar<T>(
        this IResourceBuilder<T> builder, string appId) where T : IResource
    {
        return builder.WithDaprSidecar(new DaprSidecarOptions { AppId = appId });
    }
```

Also, the _name_ (or `appId`) seems to also be required on the client-side when invoking an HTTP request. How else would that happen without the name?

> 3. The mega code sample show not show the most complex configuration, it should show the most basic configuration and then explain that more advanced configuration is possible with `AddDapr` and `WithSideCar`.

I'm not sure I agree, while it is desirable to show the basics, this is a framework integration and it's not much more complex than the official sample in the aspire-samples repo. But I could try to incorporate an adjustment to reposition the content a bit to show barebones, then config as suggested.

> 4. We don't talk about using dapr components with the API. There are 2 strongly typed ones modeled using aspire APIs and then there are all of the yaml based OSS components.

Ah, so [this section](https://learn.microsoft.com/en-us/dotnet/aspire/frameworks/dapr?tabs=dotnet-cli#adding-the-dapr-sdk) should instead show the Dapr component, right? That makes sense, I'll update that.

**Comment by davidfowl** [comment]
> The triple slash for the WithDaprSidecar needs to state that at the bare minimum. It's completely unreasonable for a consumer to make the assumption that a call to WithDaprSidecar also calls AddDapr.

Sounds good to me.

> It's not optional, it's a non-nullable appId parameter. Not according to the [source code, see here](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/IDistributedApplicationComponentBuilderExtensions.cs#L21):

Sure it is! Look at our samples for dapr. The overload is here https://github.com/dotnet/aspire/blob/460d1c39b2168d03cdf50c4af335841f327e46cf/src/Aspire.Hosting.Dapr/IDistributedApplicationComponentBuilderExtensions.cs#L34.

Example:

https://github.com/dotnet/aspire/blob/460d1c39b2168d03cdf50c4af335841f327e46cf/playground/dapr/AppHost/Program.cs#L6-L13

> I'm not sure I agree, while it is desirable to show the basics, this is a framework integration and it's not much more complex than the official sample in the aspire-samples repo. But I could try to incorporate an adjustment to reposition the content a bit to show barebones, then config as suggested.

I'm ok with it as long as people copy and paste it because its not required unless you are doing advanced stuff. People tend to copy and paste the code sample that has the most likely chance of working (is most complete). I worry that we'll see dapr examples with unnecessary complexity as a result of copy pasta.

**Comment by IEvangelist** [comment]
I was wrong, I assumed there was an Aspire component Nuget package for Dapr. There's only Hostsing bits... with that said, what exactly does this mean then, as I'm not sure - @davidfowl?

> We don't talk about using dapr components with the API. There are 2 strongly typed ones modeled using aspire APIs and then there are all of the yaml based OSS components.
